// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.25.1
// source: proto/config/config.proto

package config

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 系统配置相关消息
type SystemConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Category      string                 `protobuf:"bytes,5,opt,name=category,proto3" json:"category,omitempty"`
	IsPublic      bool                   `protobuf:"varint,6,opt,name=is_public,json=isPublic,proto3" json:"is_public,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemConfig) Reset() {
	*x = SystemConfig{}
	mi := &file_proto_config_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemConfig) ProtoMessage() {}

func (x *SystemConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemConfig.ProtoReflect.Descriptor instead.
func (*SystemConfig) Descriptor() ([]byte, []int) {
	return file_proto_config_config_proto_rawDescGZIP(), []int{0}
}

func (x *SystemConfig) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SystemConfig) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SystemConfig) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *SystemConfig) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SystemConfig) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *SystemConfig) GetIsPublic() bool {
	if x != nil {
		return x.IsPublic
	}
	return false
}

func (x *SystemConfig) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type GetSystemConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSystemConfigRequest) Reset() {
	*x = GetSystemConfigRequest{}
	mi := &file_proto_config_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSystemConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSystemConfigRequest) ProtoMessage() {}

func (x *GetSystemConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSystemConfigRequest.ProtoReflect.Descriptor instead.
func (*GetSystemConfigRequest) Descriptor() ([]byte, []int) {
	return file_proto_config_config_proto_rawDescGZIP(), []int{1}
}

func (x *GetSystemConfigRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type UpdateSystemConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSystemConfigRequest) Reset() {
	*x = UpdateSystemConfigRequest{}
	mi := &file_proto_config_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSystemConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSystemConfigRequest) ProtoMessage() {}

func (x *UpdateSystemConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSystemConfigRequest.ProtoReflect.Descriptor instead.
func (*UpdateSystemConfigRequest) Descriptor() ([]byte, []int) {
	return file_proto_config_config_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateSystemConfigRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *UpdateSystemConfigRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *UpdateSystemConfigRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type SystemConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *SystemConfig          `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemConfigResponse) Reset() {
	*x = SystemConfigResponse{}
	mi := &file_proto_config_config_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemConfigResponse) ProtoMessage() {}

func (x *SystemConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_config_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemConfigResponse.ProtoReflect.Descriptor instead.
func (*SystemConfigResponse) Descriptor() ([]byte, []int) {
	return file_proto_config_config_proto_rawDescGZIP(), []int{3}
}

func (x *SystemConfigResponse) GetConfig() *SystemConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type ListSystemConfigsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      string                 `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	IsPublic      bool                   `protobuf:"varint,2,opt,name=is_public,json=isPublic,proto3" json:"is_public,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSystemConfigsRequest) Reset() {
	*x = ListSystemConfigsRequest{}
	mi := &file_proto_config_config_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSystemConfigsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSystemConfigsRequest) ProtoMessage() {}

func (x *ListSystemConfigsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_config_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSystemConfigsRequest.ProtoReflect.Descriptor instead.
func (*ListSystemConfigsRequest) Descriptor() ([]byte, []int) {
	return file_proto_config_config_proto_rawDescGZIP(), []int{4}
}

func (x *ListSystemConfigsRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ListSystemConfigsRequest) GetIsPublic() bool {
	if x != nil {
		return x.IsPublic
	}
	return false
}

func (x *ListSystemConfigsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListSystemConfigsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListSystemConfigsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Configs       []*SystemConfig        `protobuf:"bytes,1,rep,name=configs,proto3" json:"configs,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSystemConfigsResponse) Reset() {
	*x = ListSystemConfigsResponse{}
	mi := &file_proto_config_config_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSystemConfigsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSystemConfigsResponse) ProtoMessage() {}

func (x *ListSystemConfigsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_config_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSystemConfigsResponse.ProtoReflect.Descriptor instead.
func (*ListSystemConfigsResponse) Descriptor() ([]byte, []int) {
	return file_proto_config_config_proto_rawDescGZIP(), []int{5}
}

func (x *ListSystemConfigsResponse) GetConfigs() []*SystemConfig {
	if x != nil {
		return x.Configs
	}
	return nil
}

func (x *ListSystemConfigsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

// 商户配置相关消息
type MerchantConfig struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	MerchantId          string                 `protobuf:"bytes,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	AutoSettlement      bool                   `protobuf:"varint,2,opt,name=auto_settlement,json=autoSettlement,proto3" json:"auto_settlement,omitempty"`
	SettlementCycle     int32                  `protobuf:"varint,3,opt,name=settlement_cycle,json=settlementCycle,proto3" json:"settlement_cycle,omitempty"`
	MinSettlementAmount int64                  `protobuf:"varint,4,opt,name=min_settlement_amount,json=minSettlementAmount,proto3" json:"min_settlement_amount,omitempty"`
	WebhookEnabled      bool                   `protobuf:"varint,5,opt,name=webhook_enabled,json=webhookEnabled,proto3" json:"webhook_enabled,omitempty"`
	WebhookUrl          string                 `protobuf:"bytes,6,opt,name=webhook_url,json=webhookUrl,proto3" json:"webhook_url,omitempty"`
	WebhookSecret       string                 `protobuf:"bytes,7,opt,name=webhook_secret,json=webhookSecret,proto3" json:"webhook_secret,omitempty"`
	AllowedChannels     []string               `protobuf:"bytes,8,rep,name=allowed_channels,json=allowedChannels,proto3" json:"allowed_channels,omitempty"`
	Extra               *structpb.Struct       `protobuf:"bytes,9,opt,name=extra,proto3" json:"extra,omitempty"`
	UpdatedAt           *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *MerchantConfig) Reset() {
	*x = MerchantConfig{}
	mi := &file_proto_config_config_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MerchantConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerchantConfig) ProtoMessage() {}

func (x *MerchantConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_config_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerchantConfig.ProtoReflect.Descriptor instead.
func (*MerchantConfig) Descriptor() ([]byte, []int) {
	return file_proto_config_config_proto_rawDescGZIP(), []int{6}
}

func (x *MerchantConfig) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *MerchantConfig) GetAutoSettlement() bool {
	if x != nil {
		return x.AutoSettlement
	}
	return false
}

func (x *MerchantConfig) GetSettlementCycle() int32 {
	if x != nil {
		return x.SettlementCycle
	}
	return 0
}

func (x *MerchantConfig) GetMinSettlementAmount() int64 {
	if x != nil {
		return x.MinSettlementAmount
	}
	return 0
}

func (x *MerchantConfig) GetWebhookEnabled() bool {
	if x != nil {
		return x.WebhookEnabled
	}
	return false
}

func (x *MerchantConfig) GetWebhookUrl() string {
	if x != nil {
		return x.WebhookUrl
	}
	return ""
}

func (x *MerchantConfig) GetWebhookSecret() string {
	if x != nil {
		return x.WebhookSecret
	}
	return ""
}

func (x *MerchantConfig) GetAllowedChannels() []string {
	if x != nil {
		return x.AllowedChannels
	}
	return nil
}

func (x *MerchantConfig) GetExtra() *structpb.Struct {
	if x != nil {
		return x.Extra
	}
	return nil
}

func (x *MerchantConfig) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type GetMerchantConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerchantId    string                 `protobuf:"bytes,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMerchantConfigRequest) Reset() {
	*x = GetMerchantConfigRequest{}
	mi := &file_proto_config_config_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMerchantConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMerchantConfigRequest) ProtoMessage() {}

func (x *GetMerchantConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_config_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMerchantConfigRequest.ProtoReflect.Descriptor instead.
func (*GetMerchantConfigRequest) Descriptor() ([]byte, []int) {
	return file_proto_config_config_proto_rawDescGZIP(), []int{7}
}

func (x *GetMerchantConfigRequest) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

type UpdateMerchantConfigRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	MerchantId          string                 `protobuf:"bytes,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	AutoSettlement      bool                   `protobuf:"varint,2,opt,name=auto_settlement,json=autoSettlement,proto3" json:"auto_settlement,omitempty"`
	SettlementCycle     int32                  `protobuf:"varint,3,opt,name=settlement_cycle,json=settlementCycle,proto3" json:"settlement_cycle,omitempty"`
	MinSettlementAmount int64                  `protobuf:"varint,4,opt,name=min_settlement_amount,json=minSettlementAmount,proto3" json:"min_settlement_amount,omitempty"`
	WebhookEnabled      bool                   `protobuf:"varint,5,opt,name=webhook_enabled,json=webhookEnabled,proto3" json:"webhook_enabled,omitempty"`
	WebhookUrl          string                 `protobuf:"bytes,6,opt,name=webhook_url,json=webhookUrl,proto3" json:"webhook_url,omitempty"`
	AllowedChannels     []string               `protobuf:"bytes,7,rep,name=allowed_channels,json=allowedChannels,proto3" json:"allowed_channels,omitempty"`
	Extra               *structpb.Struct       `protobuf:"bytes,8,opt,name=extra,proto3" json:"extra,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *UpdateMerchantConfigRequest) Reset() {
	*x = UpdateMerchantConfigRequest{}
	mi := &file_proto_config_config_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMerchantConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMerchantConfigRequest) ProtoMessage() {}

func (x *UpdateMerchantConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_config_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMerchantConfigRequest.ProtoReflect.Descriptor instead.
func (*UpdateMerchantConfigRequest) Descriptor() ([]byte, []int) {
	return file_proto_config_config_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateMerchantConfigRequest) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *UpdateMerchantConfigRequest) GetAutoSettlement() bool {
	if x != nil {
		return x.AutoSettlement
	}
	return false
}

func (x *UpdateMerchantConfigRequest) GetSettlementCycle() int32 {
	if x != nil {
		return x.SettlementCycle
	}
	return 0
}

func (x *UpdateMerchantConfigRequest) GetMinSettlementAmount() int64 {
	if x != nil {
		return x.MinSettlementAmount
	}
	return 0
}

func (x *UpdateMerchantConfigRequest) GetWebhookEnabled() bool {
	if x != nil {
		return x.WebhookEnabled
	}
	return false
}

func (x *UpdateMerchantConfigRequest) GetWebhookUrl() string {
	if x != nil {
		return x.WebhookUrl
	}
	return ""
}

func (x *UpdateMerchantConfigRequest) GetAllowedChannels() []string {
	if x != nil {
		return x.AllowedChannels
	}
	return nil
}

func (x *UpdateMerchantConfigRequest) GetExtra() *structpb.Struct {
	if x != nil {
		return x.Extra
	}
	return nil
}

type MerchantConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *MerchantConfig        `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MerchantConfigResponse) Reset() {
	*x = MerchantConfigResponse{}
	mi := &file_proto_config_config_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MerchantConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerchantConfigResponse) ProtoMessage() {}

func (x *MerchantConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_config_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerchantConfigResponse.ProtoReflect.Descriptor instead.
func (*MerchantConfigResponse) Descriptor() ([]byte, []int) {
	return file_proto_config_config_proto_rawDescGZIP(), []int{9}
}

func (x *MerchantConfigResponse) GetConfig() *MerchantConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

// 渠道配置相关消息
type ChannelConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Channel       string                 `protobuf:"bytes,2,opt,name=channel,proto3" json:"channel,omitempty"`
	MerchantId    string                 `protobuf:"bytes,3,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	Credentials   *structpb.Struct       `protobuf:"bytes,4,opt,name=credentials,proto3" json:"credentials,omitempty"`
	Enabled       bool                   `protobuf:"varint,5,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Priority      int32                  `protobuf:"varint,6,opt,name=priority,proto3" json:"priority,omitempty"`
	Extra         *structpb.Struct       `protobuf:"bytes,7,opt,name=extra,proto3" json:"extra,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelConfig) Reset() {
	*x = ChannelConfig{}
	mi := &file_proto_config_config_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelConfig) ProtoMessage() {}

func (x *ChannelConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_config_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelConfig.ProtoReflect.Descriptor instead.
func (*ChannelConfig) Descriptor() ([]byte, []int) {
	return file_proto_config_config_proto_rawDescGZIP(), []int{10}
}

func (x *ChannelConfig) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChannelConfig) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *ChannelConfig) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *ChannelConfig) GetCredentials() *structpb.Struct {
	if x != nil {
		return x.Credentials
	}
	return nil
}

func (x *ChannelConfig) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *ChannelConfig) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *ChannelConfig) GetExtra() *structpb.Struct {
	if x != nil {
		return x.Extra
	}
	return nil
}

func (x *ChannelConfig) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ChannelConfig) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type GetChannelConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerchantId    string                 `protobuf:"bytes,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	Channel       string                 `protobuf:"bytes,2,opt,name=channel,proto3" json:"channel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChannelConfigRequest) Reset() {
	*x = GetChannelConfigRequest{}
	mi := &file_proto_config_config_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChannelConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChannelConfigRequest) ProtoMessage() {}

func (x *GetChannelConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_config_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChannelConfigRequest.ProtoReflect.Descriptor instead.
func (*GetChannelConfigRequest) Descriptor() ([]byte, []int) {
	return file_proto_config_config_proto_rawDescGZIP(), []int{11}
}

func (x *GetChannelConfigRequest) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *GetChannelConfigRequest) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

type UpdateChannelConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerchantId    string                 `protobuf:"bytes,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	Channel       string                 `protobuf:"bytes,2,opt,name=channel,proto3" json:"channel,omitempty"`
	Credentials   *structpb.Struct       `protobuf:"bytes,3,opt,name=credentials,proto3" json:"credentials,omitempty"`
	Enabled       bool                   `protobuf:"varint,4,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Priority      int32                  `protobuf:"varint,5,opt,name=priority,proto3" json:"priority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateChannelConfigRequest) Reset() {
	*x = UpdateChannelConfigRequest{}
	mi := &file_proto_config_config_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateChannelConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateChannelConfigRequest) ProtoMessage() {}

func (x *UpdateChannelConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_config_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateChannelConfigRequest.ProtoReflect.Descriptor instead.
func (*UpdateChannelConfigRequest) Descriptor() ([]byte, []int) {
	return file_proto_config_config_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateChannelConfigRequest) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *UpdateChannelConfigRequest) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *UpdateChannelConfigRequest) GetCredentials() *structpb.Struct {
	if x != nil {
		return x.Credentials
	}
	return nil
}

func (x *UpdateChannelConfigRequest) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *UpdateChannelConfigRequest) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

type ChannelConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *ChannelConfig         `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelConfigResponse) Reset() {
	*x = ChannelConfigResponse{}
	mi := &file_proto_config_config_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelConfigResponse) ProtoMessage() {}

func (x *ChannelConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_config_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelConfigResponse.ProtoReflect.Descriptor instead.
func (*ChannelConfigResponse) Descriptor() ([]byte, []int) {
	return file_proto_config_config_proto_rawDescGZIP(), []int{13}
}

func (x *ChannelConfigResponse) GetConfig() *ChannelConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type ListChannelConfigsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerchantId    string                 `protobuf:"bytes,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	EnabledOnly   bool                   `protobuf:"varint,2,opt,name=enabled_only,json=enabledOnly,proto3" json:"enabled_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChannelConfigsRequest) Reset() {
	*x = ListChannelConfigsRequest{}
	mi := &file_proto_config_config_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChannelConfigsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChannelConfigsRequest) ProtoMessage() {}

func (x *ListChannelConfigsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_config_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChannelConfigsRequest.ProtoReflect.Descriptor instead.
func (*ListChannelConfigsRequest) Descriptor() ([]byte, []int) {
	return file_proto_config_config_proto_rawDescGZIP(), []int{14}
}

func (x *ListChannelConfigsRequest) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *ListChannelConfigsRequest) GetEnabledOnly() bool {
	if x != nil {
		return x.EnabledOnly
	}
	return false
}

type ListChannelConfigsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Configs       []*ChannelConfig       `protobuf:"bytes,1,rep,name=configs,proto3" json:"configs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChannelConfigsResponse) Reset() {
	*x = ListChannelConfigsResponse{}
	mi := &file_proto_config_config_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChannelConfigsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChannelConfigsResponse) ProtoMessage() {}

func (x *ListChannelConfigsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_config_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChannelConfigsResponse.ProtoReflect.Descriptor instead.
func (*ListChannelConfigsResponse) Descriptor() ([]byte, []int) {
	return file_proto_config_config_proto_rawDescGZIP(), []int{15}
}

func (x *ListChannelConfigsResponse) GetConfigs() []*ChannelConfig {
	if x != nil {
		return x.Configs
	}
	return nil
}

// 费率配置相关消息
type FeeConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MerchantId    string                 `protobuf:"bytes,2,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	Channel       string                 `protobuf:"bytes,3,opt,name=channel,proto3" json:"channel,omitempty"`
	PaymentMethod string                 `protobuf:"bytes,4,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	FeeRate       float64                `protobuf:"fixed64,5,opt,name=fee_rate,json=feeRate,proto3" json:"fee_rate,omitempty"`
	FixedFee      int64                  `protobuf:"varint,6,opt,name=fixed_fee,json=fixedFee,proto3" json:"fixed_fee,omitempty"`
	MinFee        int64                  `protobuf:"varint,7,opt,name=min_fee,json=minFee,proto3" json:"min_fee,omitempty"`
	MaxFee        int64                  `protobuf:"varint,8,opt,name=max_fee,json=maxFee,proto3" json:"max_fee,omitempty"`
	Currency      string                 `protobuf:"bytes,9,opt,name=currency,proto3" json:"currency,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeeConfig) Reset() {
	*x = FeeConfig{}
	mi := &file_proto_config_config_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeeConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeeConfig) ProtoMessage() {}

func (x *FeeConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_config_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeeConfig.ProtoReflect.Descriptor instead.
func (*FeeConfig) Descriptor() ([]byte, []int) {
	return file_proto_config_config_proto_rawDescGZIP(), []int{16}
}

func (x *FeeConfig) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FeeConfig) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *FeeConfig) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *FeeConfig) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *FeeConfig) GetFeeRate() float64 {
	if x != nil {
		return x.FeeRate
	}
	return 0
}

func (x *FeeConfig) GetFixedFee() int64 {
	if x != nil {
		return x.FixedFee
	}
	return 0
}

func (x *FeeConfig) GetMinFee() int64 {
	if x != nil {
		return x.MinFee
	}
	return 0
}

func (x *FeeConfig) GetMaxFee() int64 {
	if x != nil {
		return x.MaxFee
	}
	return 0
}

func (x *FeeConfig) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *FeeConfig) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type GetFeeConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerchantId    string                 `protobuf:"bytes,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	Channel       string                 `protobuf:"bytes,2,opt,name=channel,proto3" json:"channel,omitempty"`
	PaymentMethod string                 `protobuf:"bytes,3,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFeeConfigRequest) Reset() {
	*x = GetFeeConfigRequest{}
	mi := &file_proto_config_config_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFeeConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFeeConfigRequest) ProtoMessage() {}

func (x *GetFeeConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_config_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFeeConfigRequest.ProtoReflect.Descriptor instead.
func (*GetFeeConfigRequest) Descriptor() ([]byte, []int) {
	return file_proto_config_config_proto_rawDescGZIP(), []int{17}
}

func (x *GetFeeConfigRequest) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *GetFeeConfigRequest) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *GetFeeConfigRequest) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

type UpdateFeeConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerchantId    string                 `protobuf:"bytes,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	Channel       string                 `protobuf:"bytes,2,opt,name=channel,proto3" json:"channel,omitempty"`
	PaymentMethod string                 `protobuf:"bytes,3,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	FeeRate       float64                `protobuf:"fixed64,4,opt,name=fee_rate,json=feeRate,proto3" json:"fee_rate,omitempty"`
	FixedFee      int64                  `protobuf:"varint,5,opt,name=fixed_fee,json=fixedFee,proto3" json:"fixed_fee,omitempty"`
	MinFee        int64                  `protobuf:"varint,6,opt,name=min_fee,json=minFee,proto3" json:"min_fee,omitempty"`
	MaxFee        int64                  `protobuf:"varint,7,opt,name=max_fee,json=maxFee,proto3" json:"max_fee,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFeeConfigRequest) Reset() {
	*x = UpdateFeeConfigRequest{}
	mi := &file_proto_config_config_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFeeConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFeeConfigRequest) ProtoMessage() {}

func (x *UpdateFeeConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_config_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFeeConfigRequest.ProtoReflect.Descriptor instead.
func (*UpdateFeeConfigRequest) Descriptor() ([]byte, []int) {
	return file_proto_config_config_proto_rawDescGZIP(), []int{18}
}

func (x *UpdateFeeConfigRequest) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *UpdateFeeConfigRequest) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *UpdateFeeConfigRequest) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *UpdateFeeConfigRequest) GetFeeRate() float64 {
	if x != nil {
		return x.FeeRate
	}
	return 0
}

func (x *UpdateFeeConfigRequest) GetFixedFee() int64 {
	if x != nil {
		return x.FixedFee
	}
	return 0
}

func (x *UpdateFeeConfigRequest) GetMinFee() int64 {
	if x != nil {
		return x.MinFee
	}
	return 0
}

func (x *UpdateFeeConfigRequest) GetMaxFee() int64 {
	if x != nil {
		return x.MaxFee
	}
	return 0
}

type FeeConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *FeeConfig             `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeeConfigResponse) Reset() {
	*x = FeeConfigResponse{}
	mi := &file_proto_config_config_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeeConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeeConfigResponse) ProtoMessage() {}

func (x *FeeConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_config_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeeConfigResponse.ProtoReflect.Descriptor instead.
func (*FeeConfigResponse) Descriptor() ([]byte, []int) {
	return file_proto_config_config_proto_rawDescGZIP(), []int{19}
}

func (x *FeeConfigResponse) GetConfig() *FeeConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

// 限额配置相关消息
type LimitConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MerchantId    string                 `protobuf:"bytes,2,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	LimitType     string                 `protobuf:"bytes,3,opt,name=limit_type,json=limitType,proto3" json:"limit_type,omitempty"`
	SingleMin     int64                  `protobuf:"varint,4,opt,name=single_min,json=singleMin,proto3" json:"single_min,omitempty"`
	SingleMax     int64                  `protobuf:"varint,5,opt,name=single_max,json=singleMax,proto3" json:"single_max,omitempty"`
	DailyMax      int64                  `protobuf:"varint,6,opt,name=daily_max,json=dailyMax,proto3" json:"daily_max,omitempty"`
	MonthlyMax    int64                  `protobuf:"varint,7,opt,name=monthly_max,json=monthlyMax,proto3" json:"monthly_max,omitempty"`
	Currency      string                 `protobuf:"bytes,8,opt,name=currency,proto3" json:"currency,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LimitConfig) Reset() {
	*x = LimitConfig{}
	mi := &file_proto_config_config_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LimitConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LimitConfig) ProtoMessage() {}

func (x *LimitConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_config_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LimitConfig.ProtoReflect.Descriptor instead.
func (*LimitConfig) Descriptor() ([]byte, []int) {
	return file_proto_config_config_proto_rawDescGZIP(), []int{20}
}

func (x *LimitConfig) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LimitConfig) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *LimitConfig) GetLimitType() string {
	if x != nil {
		return x.LimitType
	}
	return ""
}

func (x *LimitConfig) GetSingleMin() int64 {
	if x != nil {
		return x.SingleMin
	}
	return 0
}

func (x *LimitConfig) GetSingleMax() int64 {
	if x != nil {
		return x.SingleMax
	}
	return 0
}

func (x *LimitConfig) GetDailyMax() int64 {
	if x != nil {
		return x.DailyMax
	}
	return 0
}

func (x *LimitConfig) GetMonthlyMax() int64 {
	if x != nil {
		return x.MonthlyMax
	}
	return 0
}

func (x *LimitConfig) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *LimitConfig) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type GetLimitConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerchantId    string                 `protobuf:"bytes,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	LimitType     string                 `protobuf:"bytes,2,opt,name=limit_type,json=limitType,proto3" json:"limit_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLimitConfigRequest) Reset() {
	*x = GetLimitConfigRequest{}
	mi := &file_proto_config_config_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLimitConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLimitConfigRequest) ProtoMessage() {}

func (x *GetLimitConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_config_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLimitConfigRequest.ProtoReflect.Descriptor instead.
func (*GetLimitConfigRequest) Descriptor() ([]byte, []int) {
	return file_proto_config_config_proto_rawDescGZIP(), []int{21}
}

func (x *GetLimitConfigRequest) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *GetLimitConfigRequest) GetLimitType() string {
	if x != nil {
		return x.LimitType
	}
	return ""
}

type UpdateLimitConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerchantId    string                 `protobuf:"bytes,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	LimitType     string                 `protobuf:"bytes,2,opt,name=limit_type,json=limitType,proto3" json:"limit_type,omitempty"`
	SingleMin     int64                  `protobuf:"varint,3,opt,name=single_min,json=singleMin,proto3" json:"single_min,omitempty"`
	SingleMax     int64                  `protobuf:"varint,4,opt,name=single_max,json=singleMax,proto3" json:"single_max,omitempty"`
	DailyMax      int64                  `protobuf:"varint,5,opt,name=daily_max,json=dailyMax,proto3" json:"daily_max,omitempty"`
	MonthlyMax    int64                  `protobuf:"varint,6,opt,name=monthly_max,json=monthlyMax,proto3" json:"monthly_max,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateLimitConfigRequest) Reset() {
	*x = UpdateLimitConfigRequest{}
	mi := &file_proto_config_config_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLimitConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLimitConfigRequest) ProtoMessage() {}

func (x *UpdateLimitConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_config_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLimitConfigRequest.ProtoReflect.Descriptor instead.
func (*UpdateLimitConfigRequest) Descriptor() ([]byte, []int) {
	return file_proto_config_config_proto_rawDescGZIP(), []int{22}
}

func (x *UpdateLimitConfigRequest) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *UpdateLimitConfigRequest) GetLimitType() string {
	if x != nil {
		return x.LimitType
	}
	return ""
}

func (x *UpdateLimitConfigRequest) GetSingleMin() int64 {
	if x != nil {
		return x.SingleMin
	}
	return 0
}

func (x *UpdateLimitConfigRequest) GetSingleMax() int64 {
	if x != nil {
		return x.SingleMax
	}
	return 0
}

func (x *UpdateLimitConfigRequest) GetDailyMax() int64 {
	if x != nil {
		return x.DailyMax
	}
	return 0
}

func (x *UpdateLimitConfigRequest) GetMonthlyMax() int64 {
	if x != nil {
		return x.MonthlyMax
	}
	return 0
}

type LimitConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *LimitConfig           `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LimitConfigResponse) Reset() {
	*x = LimitConfigResponse{}
	mi := &file_proto_config_config_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LimitConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LimitConfigResponse) ProtoMessage() {}

func (x *LimitConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_config_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LimitConfigResponse.ProtoReflect.Descriptor instead.
func (*LimitConfigResponse) Descriptor() ([]byte, []int) {
	return file_proto_config_config_proto_rawDescGZIP(), []int{23}
}

func (x *LimitConfigResponse) GetConfig() *LimitConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

var File_proto_config_config_proto protoreflect.FileDescriptor

const file_proto_config_config_proto_rawDesc = "" +
	"\n" +
	"\x19proto/config/config.proto\x12\x06config\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xdc\x01\n" +
	"\fSystemConfig\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1a\n" +
	"\bcategory\x18\x05 \x01(\tR\bcategory\x12\x1b\n" +
	"\tis_public\x18\x06 \x01(\bR\bisPublic\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"*\n" +
	"\x16GetSystemConfigRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"e\n" +
	"\x19UpdateSystemConfigRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"D\n" +
	"\x14SystemConfigResponse\x12,\n" +
	"\x06config\x18\x01 \x01(\v2\x14.config.SystemConfigR\x06config\"\x84\x01\n" +
	"\x18ListSystemConfigsRequest\x12\x1a\n" +
	"\bcategory\x18\x01 \x01(\tR\bcategory\x12\x1b\n" +
	"\tis_public\x18\x02 \x01(\bR\bisPublic\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"a\n" +
	"\x19ListSystemConfigsResponse\x12.\n" +
	"\aconfigs\x18\x01 \x03(\v2\x14.config.SystemConfigR\aconfigs\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\xbf\x03\n" +
	"\x0eMerchantConfig\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\tR\n" +
	"merchantId\x12'\n" +
	"\x0fauto_settlement\x18\x02 \x01(\bR\x0eautoSettlement\x12)\n" +
	"\x10settlement_cycle\x18\x03 \x01(\x05R\x0fsettlementCycle\x122\n" +
	"\x15min_settlement_amount\x18\x04 \x01(\x03R\x13minSettlementAmount\x12'\n" +
	"\x0fwebhook_enabled\x18\x05 \x01(\bR\x0ewebhookEnabled\x12\x1f\n" +
	"\vwebhook_url\x18\x06 \x01(\tR\n" +
	"webhookUrl\x12%\n" +
	"\x0ewebhook_secret\x18\a \x01(\tR\rwebhookSecret\x12)\n" +
	"\x10allowed_channels\x18\b \x03(\tR\x0fallowedChannels\x12-\n" +
	"\x05extra\x18\t \x01(\v2\x17.google.protobuf.StructR\x05extra\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\";\n" +
	"\x18GetMerchantConfigRequest\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\tR\n" +
	"merchantId\"\xea\x02\n" +
	"\x1bUpdateMerchantConfigRequest\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\tR\n" +
	"merchantId\x12'\n" +
	"\x0fauto_settlement\x18\x02 \x01(\bR\x0eautoSettlement\x12)\n" +
	"\x10settlement_cycle\x18\x03 \x01(\x05R\x0fsettlementCycle\x122\n" +
	"\x15min_settlement_amount\x18\x04 \x01(\x03R\x13minSettlementAmount\x12'\n" +
	"\x0fwebhook_enabled\x18\x05 \x01(\bR\x0ewebhookEnabled\x12\x1f\n" +
	"\vwebhook_url\x18\x06 \x01(\tR\n" +
	"webhookUrl\x12)\n" +
	"\x10allowed_channels\x18\a \x03(\tR\x0fallowedChannels\x12-\n" +
	"\x05extra\x18\b \x01(\v2\x17.google.protobuf.StructR\x05extra\"H\n" +
	"\x16MerchantConfigResponse\x12.\n" +
	"\x06config\x18\x01 \x01(\v2\x16.config.MerchantConfigR\x06config\"\xf0\x02\n" +
	"\rChannelConfig\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\achannel\x18\x02 \x01(\tR\achannel\x12\x1f\n" +
	"\vmerchant_id\x18\x03 \x01(\tR\n" +
	"merchantId\x129\n" +
	"\vcredentials\x18\x04 \x01(\v2\x17.google.protobuf.StructR\vcredentials\x12\x18\n" +
	"\aenabled\x18\x05 \x01(\bR\aenabled\x12\x1a\n" +
	"\bpriority\x18\x06 \x01(\x05R\bpriority\x12-\n" +
	"\x05extra\x18\a \x01(\v2\x17.google.protobuf.StructR\x05extra\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"T\n" +
	"\x17GetChannelConfigRequest\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\tR\n" +
	"merchantId\x12\x18\n" +
	"\achannel\x18\x02 \x01(\tR\achannel\"\xc8\x01\n" +
	"\x1aUpdateChannelConfigRequest\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\tR\n" +
	"merchantId\x12\x18\n" +
	"\achannel\x18\x02 \x01(\tR\achannel\x129\n" +
	"\vcredentials\x18\x03 \x01(\v2\x17.google.protobuf.StructR\vcredentials\x12\x18\n" +
	"\aenabled\x18\x04 \x01(\bR\aenabled\x12\x1a\n" +
	"\bpriority\x18\x05 \x01(\x05R\bpriority\"F\n" +
	"\x15ChannelConfigResponse\x12-\n" +
	"\x06config\x18\x01 \x01(\v2\x15.config.ChannelConfigR\x06config\"_\n" +
	"\x19ListChannelConfigsRequest\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\tR\n" +
	"merchantId\x12!\n" +
	"\fenabled_only\x18\x02 \x01(\bR\venabledOnly\"M\n" +
	"\x1aListChannelConfigsResponse\x12/\n" +
	"\aconfigs\x18\x01 \x03(\v2\x15.config.ChannelConfigR\aconfigs\"\xbe\x02\n" +
	"\tFeeConfig\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vmerchant_id\x18\x02 \x01(\tR\n" +
	"merchantId\x12\x18\n" +
	"\achannel\x18\x03 \x01(\tR\achannel\x12%\n" +
	"\x0epayment_method\x18\x04 \x01(\tR\rpaymentMethod\x12\x19\n" +
	"\bfee_rate\x18\x05 \x01(\x01R\afeeRate\x12\x1b\n" +
	"\tfixed_fee\x18\x06 \x01(\x03R\bfixedFee\x12\x17\n" +
	"\amin_fee\x18\a \x01(\x03R\x06minFee\x12\x17\n" +
	"\amax_fee\x18\b \x01(\x03R\x06maxFee\x12\x1a\n" +
	"\bcurrency\x18\t \x01(\tR\bcurrency\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"w\n" +
	"\x13GetFeeConfigRequest\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\tR\n" +
	"merchantId\x12\x18\n" +
	"\achannel\x18\x02 \x01(\tR\achannel\x12%\n" +
	"\x0epayment_method\x18\x03 \x01(\tR\rpaymentMethod\"\xe4\x01\n" +
	"\x16UpdateFeeConfigRequest\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\tR\n" +
	"merchantId\x12\x18\n" +
	"\achannel\x18\x02 \x01(\tR\achannel\x12%\n" +
	"\x0epayment_method\x18\x03 \x01(\tR\rpaymentMethod\x12\x19\n" +
	"\bfee_rate\x18\x04 \x01(\x01R\afeeRate\x12\x1b\n" +
	"\tfixed_fee\x18\x05 \x01(\x03R\bfixedFee\x12\x17\n" +
	"\amin_fee\x18\x06 \x01(\x03R\x06minFee\x12\x17\n" +
	"\amax_fee\x18\a \x01(\x03R\x06maxFee\">\n" +
	"\x11FeeConfigResponse\x12)\n" +
	"\x06config\x18\x01 \x01(\v2\x11.config.FeeConfigR\x06config\"\xb0\x02\n" +
	"\vLimitConfig\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vmerchant_id\x18\x02 \x01(\tR\n" +
	"merchantId\x12\x1d\n" +
	"\n" +
	"limit_type\x18\x03 \x01(\tR\tlimitType\x12\x1d\n" +
	"\n" +
	"single_min\x18\x04 \x01(\x03R\tsingleMin\x12\x1d\n" +
	"\n" +
	"single_max\x18\x05 \x01(\x03R\tsingleMax\x12\x1b\n" +
	"\tdaily_max\x18\x06 \x01(\x03R\bdailyMax\x12\x1f\n" +
	"\vmonthly_max\x18\a \x01(\x03R\n" +
	"monthlyMax\x12\x1a\n" +
	"\bcurrency\x18\b \x01(\tR\bcurrency\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"W\n" +
	"\x15GetLimitConfigRequest\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\tR\n" +
	"merchantId\x12\x1d\n" +
	"\n" +
	"limit_type\x18\x02 \x01(\tR\tlimitType\"\xd6\x01\n" +
	"\x18UpdateLimitConfigRequest\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\tR\n" +
	"merchantId\x12\x1d\n" +
	"\n" +
	"limit_type\x18\x02 \x01(\tR\tlimitType\x12\x1d\n" +
	"\n" +
	"single_min\x18\x03 \x01(\x03R\tsingleMin\x12\x1d\n" +
	"\n" +
	"single_max\x18\x04 \x01(\x03R\tsingleMax\x12\x1b\n" +
	"\tdaily_max\x18\x05 \x01(\x03R\bdailyMax\x12\x1f\n" +
	"\vmonthly_max\x18\x06 \x01(\x03R\n" +
	"monthlyMax\"B\n" +
	"\x13LimitConfigResponse\x12+\n" +
	"\x06config\x18\x01 \x01(\v2\x13.config.LimitConfigR\x06config2\x88\b\n" +
	"\rConfigService\x12O\n" +
	"\x0fGetSystemConfig\x12\x1e.config.GetSystemConfigRequest\x1a\x1c.config.SystemConfigResponse\x12U\n" +
	"\x12UpdateSystemConfig\x12!.config.UpdateSystemConfigRequest\x1a\x1c.config.SystemConfigResponse\x12X\n" +
	"\x11ListSystemConfigs\x12 .config.ListSystemConfigsRequest\x1a!.config.ListSystemConfigsResponse\x12U\n" +
	"\x11GetMerchantConfig\x12 .config.GetMerchantConfigRequest\x1a\x1e.config.MerchantConfigResponse\x12[\n" +
	"\x14UpdateMerchantConfig\x12#.config.UpdateMerchantConfigRequest\x1a\x1e.config.MerchantConfigResponse\x12R\n" +
	"\x10GetChannelConfig\x12\x1f.config.GetChannelConfigRequest\x1a\x1d.config.ChannelConfigResponse\x12X\n" +
	"\x13UpdateChannelConfig\x12\".config.UpdateChannelConfigRequest\x1a\x1d.config.ChannelConfigResponse\x12[\n" +
	"\x12ListChannelConfigs\x12!.config.ListChannelConfigsRequest\x1a\".config.ListChannelConfigsResponse\x12F\n" +
	"\fGetFeeConfig\x12\x1b.config.GetFeeConfigRequest\x1a\x19.config.FeeConfigResponse\x12L\n" +
	"\x0fUpdateFeeConfig\x12\x1e.config.UpdateFeeConfigRequest\x1a\x19.config.FeeConfigResponse\x12L\n" +
	"\x0eGetLimitConfig\x12\x1d.config.GetLimitConfigRequest\x1a\x1b.config.LimitConfigResponse\x12R\n" +
	"\x11UpdateLimitConfig\x12 .config.UpdateLimitConfigRequest\x1a\x1b.config.LimitConfigResponseB1Z/github.com/payment-platform/proto/config;configb\x06proto3"

var (
	file_proto_config_config_proto_rawDescOnce sync.Once
	file_proto_config_config_proto_rawDescData []byte
)

func file_proto_config_config_proto_rawDescGZIP() []byte {
	file_proto_config_config_proto_rawDescOnce.Do(func() {
		file_proto_config_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_config_config_proto_rawDesc), len(file_proto_config_config_proto_rawDesc)))
	})
	return file_proto_config_config_proto_rawDescData
}

var file_proto_config_config_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_proto_config_config_proto_goTypes = []any{
	(*SystemConfig)(nil),                // 0: config.SystemConfig
	(*GetSystemConfigRequest)(nil),      // 1: config.GetSystemConfigRequest
	(*UpdateSystemConfigRequest)(nil),   // 2: config.UpdateSystemConfigRequest
	(*SystemConfigResponse)(nil),        // 3: config.SystemConfigResponse
	(*ListSystemConfigsRequest)(nil),    // 4: config.ListSystemConfigsRequest
	(*ListSystemConfigsResponse)(nil),   // 5: config.ListSystemConfigsResponse
	(*MerchantConfig)(nil),              // 6: config.MerchantConfig
	(*GetMerchantConfigRequest)(nil),    // 7: config.GetMerchantConfigRequest
	(*UpdateMerchantConfigRequest)(nil), // 8: config.UpdateMerchantConfigRequest
	(*MerchantConfigResponse)(nil),      // 9: config.MerchantConfigResponse
	(*ChannelConfig)(nil),               // 10: config.ChannelConfig
	(*GetChannelConfigRequest)(nil),     // 11: config.GetChannelConfigRequest
	(*UpdateChannelConfigRequest)(nil),  // 12: config.UpdateChannelConfigRequest
	(*ChannelConfigResponse)(nil),       // 13: config.ChannelConfigResponse
	(*ListChannelConfigsRequest)(nil),   // 14: config.ListChannelConfigsRequest
	(*ListChannelConfigsResponse)(nil),  // 15: config.ListChannelConfigsResponse
	(*FeeConfig)(nil),                   // 16: config.FeeConfig
	(*GetFeeConfigRequest)(nil),         // 17: config.GetFeeConfigRequest
	(*UpdateFeeConfigRequest)(nil),      // 18: config.UpdateFeeConfigRequest
	(*FeeConfigResponse)(nil),           // 19: config.FeeConfigResponse
	(*LimitConfig)(nil),                 // 20: config.LimitConfig
	(*GetLimitConfigRequest)(nil),       // 21: config.GetLimitConfigRequest
	(*UpdateLimitConfigRequest)(nil),    // 22: config.UpdateLimitConfigRequest
	(*LimitConfigResponse)(nil),         // 23: config.LimitConfigResponse
	(*timestamppb.Timestamp)(nil),       // 24: google.protobuf.Timestamp
	(*structpb.Struct)(nil),             // 25: google.protobuf.Struct
}
var file_proto_config_config_proto_depIdxs = []int32{
	24, // 0: config.SystemConfig.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 1: config.SystemConfigResponse.config:type_name -> config.SystemConfig
	0,  // 2: config.ListSystemConfigsResponse.configs:type_name -> config.SystemConfig
	25, // 3: config.MerchantConfig.extra:type_name -> google.protobuf.Struct
	24, // 4: config.MerchantConfig.updated_at:type_name -> google.protobuf.Timestamp
	25, // 5: config.UpdateMerchantConfigRequest.extra:type_name -> google.protobuf.Struct
	6,  // 6: config.MerchantConfigResponse.config:type_name -> config.MerchantConfig
	25, // 7: config.ChannelConfig.credentials:type_name -> google.protobuf.Struct
	25, // 8: config.ChannelConfig.extra:type_name -> google.protobuf.Struct
	24, // 9: config.ChannelConfig.created_at:type_name -> google.protobuf.Timestamp
	24, // 10: config.ChannelConfig.updated_at:type_name -> google.protobuf.Timestamp
	25, // 11: config.UpdateChannelConfigRequest.credentials:type_name -> google.protobuf.Struct
	10, // 12: config.ChannelConfigResponse.config:type_name -> config.ChannelConfig
	10, // 13: config.ListChannelConfigsResponse.configs:type_name -> config.ChannelConfig
	24, // 14: config.FeeConfig.updated_at:type_name -> google.protobuf.Timestamp
	16, // 15: config.FeeConfigResponse.config:type_name -> config.FeeConfig
	24, // 16: config.LimitConfig.updated_at:type_name -> google.protobuf.Timestamp
	20, // 17: config.LimitConfigResponse.config:type_name -> config.LimitConfig
	1,  // 18: config.ConfigService.GetSystemConfig:input_type -> config.GetSystemConfigRequest
	2,  // 19: config.ConfigService.UpdateSystemConfig:input_type -> config.UpdateSystemConfigRequest
	4,  // 20: config.ConfigService.ListSystemConfigs:input_type -> config.ListSystemConfigsRequest
	7,  // 21: config.ConfigService.GetMerchantConfig:input_type -> config.GetMerchantConfigRequest
	8,  // 22: config.ConfigService.UpdateMerchantConfig:input_type -> config.UpdateMerchantConfigRequest
	11, // 23: config.ConfigService.GetChannelConfig:input_type -> config.GetChannelConfigRequest
	12, // 24: config.ConfigService.UpdateChannelConfig:input_type -> config.UpdateChannelConfigRequest
	14, // 25: config.ConfigService.ListChannelConfigs:input_type -> config.ListChannelConfigsRequest
	17, // 26: config.ConfigService.GetFeeConfig:input_type -> config.GetFeeConfigRequest
	18, // 27: config.ConfigService.UpdateFeeConfig:input_type -> config.UpdateFeeConfigRequest
	21, // 28: config.ConfigService.GetLimitConfig:input_type -> config.GetLimitConfigRequest
	22, // 29: config.ConfigService.UpdateLimitConfig:input_type -> config.UpdateLimitConfigRequest
	3,  // 30: config.ConfigService.GetSystemConfig:output_type -> config.SystemConfigResponse
	3,  // 31: config.ConfigService.UpdateSystemConfig:output_type -> config.SystemConfigResponse
	5,  // 32: config.ConfigService.ListSystemConfigs:output_type -> config.ListSystemConfigsResponse
	9,  // 33: config.ConfigService.GetMerchantConfig:output_type -> config.MerchantConfigResponse
	9,  // 34: config.ConfigService.UpdateMerchantConfig:output_type -> config.MerchantConfigResponse
	13, // 35: config.ConfigService.GetChannelConfig:output_type -> config.ChannelConfigResponse
	13, // 36: config.ConfigService.UpdateChannelConfig:output_type -> config.ChannelConfigResponse
	15, // 37: config.ConfigService.ListChannelConfigs:output_type -> config.ListChannelConfigsResponse
	19, // 38: config.ConfigService.GetFeeConfig:output_type -> config.FeeConfigResponse
	19, // 39: config.ConfigService.UpdateFeeConfig:output_type -> config.FeeConfigResponse
	23, // 40: config.ConfigService.GetLimitConfig:output_type -> config.LimitConfigResponse
	23, // 41: config.ConfigService.UpdateLimitConfig:output_type -> config.LimitConfigResponse
	30, // [30:42] is the sub-list for method output_type
	18, // [18:30] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_proto_config_config_proto_init() }
func file_proto_config_config_proto_init() {
	if File_proto_config_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_config_config_proto_rawDesc), len(file_proto_config_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_config_config_proto_goTypes,
		DependencyIndexes: file_proto_config_config_proto_depIdxs,
		MessageInfos:      file_proto_config_config_proto_msgTypes,
	}.Build()
	File_proto_config_config_proto = out.File
	file_proto_config_config_proto_goTypes = nil
	file_proto_config_config_proto_depIdxs = nil
}
