// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.25.1
// source: proto/analytics/analytics.proto

package analytics

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 支付统计相关消息
type PaymentStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalCount    int64                  `protobuf:"varint,1,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	SuccessCount  int64                  `protobuf:"varint,2,opt,name=success_count,json=successCount,proto3" json:"success_count,omitempty"`
	FailedCount   int64                  `protobuf:"varint,3,opt,name=failed_count,json=failedCount,proto3" json:"failed_count,omitempty"`
	TotalAmount   int64                  `protobuf:"varint,4,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	SuccessRate   float64                `protobuf:"fixed64,5,opt,name=success_rate,json=successRate,proto3" json:"success_rate,omitempty"`
	AverageAmount float64                `protobuf:"fixed64,6,opt,name=average_amount,json=averageAmount,proto3" json:"average_amount,omitempty"`
	Currency      string                 `protobuf:"bytes,7,opt,name=currency,proto3" json:"currency,omitempty"`
	Period        string                 `protobuf:"bytes,8,opt,name=period,proto3" json:"period,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentStats) Reset() {
	*x = PaymentStats{}
	mi := &file_proto_analytics_analytics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentStats) ProtoMessage() {}

func (x *PaymentStats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_analytics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentStats.ProtoReflect.Descriptor instead.
func (*PaymentStats) Descriptor() ([]byte, []int) {
	return file_proto_analytics_analytics_proto_rawDescGZIP(), []int{0}
}

func (x *PaymentStats) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *PaymentStats) GetSuccessCount() int64 {
	if x != nil {
		return x.SuccessCount
	}
	return 0
}

func (x *PaymentStats) GetFailedCount() int64 {
	if x != nil {
		return x.FailedCount
	}
	return 0
}

func (x *PaymentStats) GetTotalAmount() int64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *PaymentStats) GetSuccessRate() float64 {
	if x != nil {
		return x.SuccessRate
	}
	return 0
}

func (x *PaymentStats) GetAverageAmount() float64 {
	if x != nil {
		return x.AverageAmount
	}
	return 0
}

func (x *PaymentStats) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *PaymentStats) GetPeriod() string {
	if x != nil {
		return x.Period
	}
	return ""
}

type GetPaymentStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerchantId    string                 `protobuf:"bytes,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Currency      string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentStatsRequest) Reset() {
	*x = GetPaymentStatsRequest{}
	mi := &file_proto_analytics_analytics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentStatsRequest) ProtoMessage() {}

func (x *GetPaymentStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_analytics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentStatsRequest.ProtoReflect.Descriptor instead.
func (*GetPaymentStatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_analytics_analytics_proto_rawDescGZIP(), []int{1}
}

func (x *GetPaymentStatsRequest) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *GetPaymentStatsRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *GetPaymentStatsRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *GetPaymentStatsRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type PaymentStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stats         *PaymentStats          `protobuf:"bytes,1,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentStatsResponse) Reset() {
	*x = PaymentStatsResponse{}
	mi := &file_proto_analytics_analytics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentStatsResponse) ProtoMessage() {}

func (x *PaymentStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_analytics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentStatsResponse.ProtoReflect.Descriptor instead.
func (*PaymentStatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_analytics_analytics_proto_rawDescGZIP(), []int{2}
}

func (x *PaymentStatsResponse) GetStats() *PaymentStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

type TrendPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Time          string                 `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	Count         int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Amount        int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrendPoint) Reset() {
	*x = TrendPoint{}
	mi := &file_proto_analytics_analytics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrendPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrendPoint) ProtoMessage() {}

func (x *TrendPoint) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_analytics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrendPoint.ProtoReflect.Descriptor instead.
func (*TrendPoint) Descriptor() ([]byte, []int) {
	return file_proto_analytics_analytics_proto_rawDescGZIP(), []int{3}
}

func (x *TrendPoint) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (x *TrendPoint) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *TrendPoint) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type GetPaymentTrendsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerchantId    string                 `protobuf:"bytes,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Granularity   string                 `protobuf:"bytes,4,opt,name=granularity,proto3" json:"granularity,omitempty"` // hour, day, week, month
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentTrendsRequest) Reset() {
	*x = GetPaymentTrendsRequest{}
	mi := &file_proto_analytics_analytics_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentTrendsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentTrendsRequest) ProtoMessage() {}

func (x *GetPaymentTrendsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_analytics_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentTrendsRequest.ProtoReflect.Descriptor instead.
func (*GetPaymentTrendsRequest) Descriptor() ([]byte, []int) {
	return file_proto_analytics_analytics_proto_rawDescGZIP(), []int{4}
}

func (x *GetPaymentTrendsRequest) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *GetPaymentTrendsRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *GetPaymentTrendsRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *GetPaymentTrendsRequest) GetGranularity() string {
	if x != nil {
		return x.Granularity
	}
	return ""
}

type PaymentTrendsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Trends        []*TrendPoint          `protobuf:"bytes,1,rep,name=trends,proto3" json:"trends,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentTrendsResponse) Reset() {
	*x = PaymentTrendsResponse{}
	mi := &file_proto_analytics_analytics_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentTrendsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentTrendsResponse) ProtoMessage() {}

func (x *PaymentTrendsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_analytics_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentTrendsResponse.ProtoReflect.Descriptor instead.
func (*PaymentTrendsResponse) Descriptor() ([]byte, []int) {
	return file_proto_analytics_analytics_proto_rawDescGZIP(), []int{5}
}

func (x *PaymentTrendsResponse) GetTrends() []*TrendPoint {
	if x != nil {
		return x.Trends
	}
	return nil
}

type ChannelStat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channel       string                 `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	Count         int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Amount        int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	SuccessRate   float64                `protobuf:"fixed64,4,opt,name=success_rate,json=successRate,proto3" json:"success_rate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelStat) Reset() {
	*x = ChannelStat{}
	mi := &file_proto_analytics_analytics_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelStat) ProtoMessage() {}

func (x *ChannelStat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_analytics_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelStat.ProtoReflect.Descriptor instead.
func (*ChannelStat) Descriptor() ([]byte, []int) {
	return file_proto_analytics_analytics_proto_rawDescGZIP(), []int{6}
}

func (x *ChannelStat) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *ChannelStat) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ChannelStat) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *ChannelStat) GetSuccessRate() float64 {
	if x != nil {
		return x.SuccessRate
	}
	return 0
}

type GetChannelStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerchantId    string                 `protobuf:"bytes,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChannelStatsRequest) Reset() {
	*x = GetChannelStatsRequest{}
	mi := &file_proto_analytics_analytics_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChannelStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChannelStatsRequest) ProtoMessage() {}

func (x *GetChannelStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_analytics_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChannelStatsRequest.ProtoReflect.Descriptor instead.
func (*GetChannelStatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_analytics_analytics_proto_rawDescGZIP(), []int{7}
}

func (x *GetChannelStatsRequest) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *GetChannelStatsRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *GetChannelStatsRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

type ChannelStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channels      []*ChannelStat         `protobuf:"bytes,1,rep,name=channels,proto3" json:"channels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelStatsResponse) Reset() {
	*x = ChannelStatsResponse{}
	mi := &file_proto_analytics_analytics_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelStatsResponse) ProtoMessage() {}

func (x *ChannelStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_analytics_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelStatsResponse.ProtoReflect.Descriptor instead.
func (*ChannelStatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_analytics_analytics_proto_rawDescGZIP(), []int{8}
}

func (x *ChannelStatsResponse) GetChannels() []*ChannelStat {
	if x != nil {
		return x.Channels
	}
	return nil
}

// 商户统计相关消息
type MerchantStats struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	MerchantId        string                 `protobuf:"bytes,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	MerchantName      string                 `protobuf:"bytes,2,opt,name=merchant_name,json=merchantName,proto3" json:"merchant_name,omitempty"`
	TotalTransactions int64                  `protobuf:"varint,3,opt,name=total_transactions,json=totalTransactions,proto3" json:"total_transactions,omitempty"`
	TotalAmount       int64                  `protobuf:"varint,4,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	ActiveUsers       int64                  `protobuf:"varint,5,opt,name=active_users,json=activeUsers,proto3" json:"active_users,omitempty"`
	ConversionRate    float64                `protobuf:"fixed64,6,opt,name=conversion_rate,json=conversionRate,proto3" json:"conversion_rate,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *MerchantStats) Reset() {
	*x = MerchantStats{}
	mi := &file_proto_analytics_analytics_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MerchantStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerchantStats) ProtoMessage() {}

func (x *MerchantStats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_analytics_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerchantStats.ProtoReflect.Descriptor instead.
func (*MerchantStats) Descriptor() ([]byte, []int) {
	return file_proto_analytics_analytics_proto_rawDescGZIP(), []int{9}
}

func (x *MerchantStats) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *MerchantStats) GetMerchantName() string {
	if x != nil {
		return x.MerchantName
	}
	return ""
}

func (x *MerchantStats) GetTotalTransactions() int64 {
	if x != nil {
		return x.TotalTransactions
	}
	return 0
}

func (x *MerchantStats) GetTotalAmount() int64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *MerchantStats) GetActiveUsers() int64 {
	if x != nil {
		return x.ActiveUsers
	}
	return 0
}

func (x *MerchantStats) GetConversionRate() float64 {
	if x != nil {
		return x.ConversionRate
	}
	return 0
}

type GetMerchantStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerchantId    string                 `protobuf:"bytes,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMerchantStatsRequest) Reset() {
	*x = GetMerchantStatsRequest{}
	mi := &file_proto_analytics_analytics_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMerchantStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMerchantStatsRequest) ProtoMessage() {}

func (x *GetMerchantStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_analytics_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMerchantStatsRequest.ProtoReflect.Descriptor instead.
func (*GetMerchantStatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_analytics_analytics_proto_rawDescGZIP(), []int{10}
}

func (x *GetMerchantStatsRequest) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *GetMerchantStatsRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *GetMerchantStatsRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

type MerchantStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stats         *MerchantStats         `protobuf:"bytes,1,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MerchantStatsResponse) Reset() {
	*x = MerchantStatsResponse{}
	mi := &file_proto_analytics_analytics_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MerchantStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerchantStatsResponse) ProtoMessage() {}

func (x *MerchantStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_analytics_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerchantStatsResponse.ProtoReflect.Descriptor instead.
func (*MerchantStatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_analytics_analytics_proto_rawDescGZIP(), []int{11}
}

func (x *MerchantStatsResponse) GetStats() *MerchantStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

type TopMerchant struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	MerchantId       string                 `protobuf:"bytes,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	MerchantName     string                 `protobuf:"bytes,2,opt,name=merchant_name,json=merchantName,proto3" json:"merchant_name,omitempty"`
	TotalAmount      int64                  `protobuf:"varint,3,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	TransactionCount int64                  `protobuf:"varint,4,opt,name=transaction_count,json=transactionCount,proto3" json:"transaction_count,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TopMerchant) Reset() {
	*x = TopMerchant{}
	mi := &file_proto_analytics_analytics_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopMerchant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopMerchant) ProtoMessage() {}

func (x *TopMerchant) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_analytics_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopMerchant.ProtoReflect.Descriptor instead.
func (*TopMerchant) Descriptor() ([]byte, []int) {
	return file_proto_analytics_analytics_proto_rawDescGZIP(), []int{12}
}

func (x *TopMerchant) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *TopMerchant) GetMerchantName() string {
	if x != nil {
		return x.MerchantName
	}
	return ""
}

func (x *TopMerchant) GetTotalAmount() int64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *TopMerchant) GetTransactionCount() int64 {
	if x != nil {
		return x.TransactionCount
	}
	return 0
}

type GetTopMerchantsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	OrderBy       string                 `protobuf:"bytes,4,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"` // amount, count
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopMerchantsRequest) Reset() {
	*x = GetTopMerchantsRequest{}
	mi := &file_proto_analytics_analytics_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopMerchantsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopMerchantsRequest) ProtoMessage() {}

func (x *GetTopMerchantsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_analytics_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopMerchantsRequest.ProtoReflect.Descriptor instead.
func (*GetTopMerchantsRequest) Descriptor() ([]byte, []int) {
	return file_proto_analytics_analytics_proto_rawDescGZIP(), []int{13}
}

func (x *GetTopMerchantsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetTopMerchantsRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *GetTopMerchantsRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *GetTopMerchantsRequest) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

type TopMerchantsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Merchants     []*TopMerchant         `protobuf:"bytes,1,rep,name=merchants,proto3" json:"merchants,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopMerchantsResponse) Reset() {
	*x = TopMerchantsResponse{}
	mi := &file_proto_analytics_analytics_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopMerchantsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopMerchantsResponse) ProtoMessage() {}

func (x *TopMerchantsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_analytics_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopMerchantsResponse.ProtoReflect.Descriptor instead.
func (*TopMerchantsResponse) Descriptor() ([]byte, []int) {
	return file_proto_analytics_analytics_proto_rawDescGZIP(), []int{14}
}

func (x *TopMerchantsResponse) GetMerchants() []*TopMerchant {
	if x != nil {
		return x.Merchants
	}
	return nil
}

// 实时监控相关消息
type RealtimeMetrics struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	ActiveSessions          int64                  `protobuf:"varint,1,opt,name=active_sessions,json=activeSessions,proto3" json:"active_sessions,omitempty"`
	RequestsPerSecond       int64                  `protobuf:"varint,2,opt,name=requests_per_second,json=requestsPerSecond,proto3" json:"requests_per_second,omitempty"`
	SuccessfulPaymentsCount int64                  `protobuf:"varint,3,opt,name=successful_payments_count,json=successfulPaymentsCount,proto3" json:"successful_payments_count,omitempty"`
	FailedPaymentsCount     int64                  `protobuf:"varint,4,opt,name=failed_payments_count,json=failedPaymentsCount,proto3" json:"failed_payments_count,omitempty"`
	AverageResponseTime     float64                `protobuf:"fixed64,5,opt,name=average_response_time,json=averageResponseTime,proto3" json:"average_response_time,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *RealtimeMetrics) Reset() {
	*x = RealtimeMetrics{}
	mi := &file_proto_analytics_analytics_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RealtimeMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RealtimeMetrics) ProtoMessage() {}

func (x *RealtimeMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_analytics_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RealtimeMetrics.ProtoReflect.Descriptor instead.
func (*RealtimeMetrics) Descriptor() ([]byte, []int) {
	return file_proto_analytics_analytics_proto_rawDescGZIP(), []int{15}
}

func (x *RealtimeMetrics) GetActiveSessions() int64 {
	if x != nil {
		return x.ActiveSessions
	}
	return 0
}

func (x *RealtimeMetrics) GetRequestsPerSecond() int64 {
	if x != nil {
		return x.RequestsPerSecond
	}
	return 0
}

func (x *RealtimeMetrics) GetSuccessfulPaymentsCount() int64 {
	if x != nil {
		return x.SuccessfulPaymentsCount
	}
	return 0
}

func (x *RealtimeMetrics) GetFailedPaymentsCount() int64 {
	if x != nil {
		return x.FailedPaymentsCount
	}
	return 0
}

func (x *RealtimeMetrics) GetAverageResponseTime() float64 {
	if x != nil {
		return x.AverageResponseTime
	}
	return 0
}

type GetRealtimeMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimeRange     string                 `protobuf:"bytes,1,opt,name=time_range,json=timeRange,proto3" json:"time_range,omitempty"` // 1m, 5m, 15m
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRealtimeMetricsRequest) Reset() {
	*x = GetRealtimeMetricsRequest{}
	mi := &file_proto_analytics_analytics_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRealtimeMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRealtimeMetricsRequest) ProtoMessage() {}

func (x *GetRealtimeMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_analytics_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRealtimeMetricsRequest.ProtoReflect.Descriptor instead.
func (*GetRealtimeMetricsRequest) Descriptor() ([]byte, []int) {
	return file_proto_analytics_analytics_proto_rawDescGZIP(), []int{16}
}

func (x *GetRealtimeMetricsRequest) GetTimeRange() string {
	if x != nil {
		return x.TimeRange
	}
	return ""
}

type RealtimeMetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metrics       *RealtimeMetrics       `protobuf:"bytes,1,opt,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RealtimeMetricsResponse) Reset() {
	*x = RealtimeMetricsResponse{}
	mi := &file_proto_analytics_analytics_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RealtimeMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RealtimeMetricsResponse) ProtoMessage() {}

func (x *RealtimeMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_analytics_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RealtimeMetricsResponse.ProtoReflect.Descriptor instead.
func (*RealtimeMetricsResponse) Descriptor() ([]byte, []int) {
	return file_proto_analytics_analytics_proto_rawDescGZIP(), []int{17}
}

func (x *RealtimeMetricsResponse) GetMetrics() *RealtimeMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type ServiceHealth struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	CpuUsage      float64                `protobuf:"fixed64,3,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	MemoryUsage   float64                `protobuf:"fixed64,4,opt,name=memory_usage,json=memoryUsage,proto3" json:"memory_usage,omitempty"`
	RequestCount  int64                  `protobuf:"varint,5,opt,name=request_count,json=requestCount,proto3" json:"request_count,omitempty"`
	ErrorRate     float64                `protobuf:"fixed64,6,opt,name=error_rate,json=errorRate,proto3" json:"error_rate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceHealth) Reset() {
	*x = ServiceHealth{}
	mi := &file_proto_analytics_analytics_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceHealth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceHealth) ProtoMessage() {}

func (x *ServiceHealth) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_analytics_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceHealth.ProtoReflect.Descriptor instead.
func (*ServiceHealth) Descriptor() ([]byte, []int) {
	return file_proto_analytics_analytics_proto_rawDescGZIP(), []int{18}
}

func (x *ServiceHealth) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *ServiceHealth) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ServiceHealth) GetCpuUsage() float64 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *ServiceHealth) GetMemoryUsage() float64 {
	if x != nil {
		return x.MemoryUsage
	}
	return 0
}

func (x *ServiceHealth) GetRequestCount() int64 {
	if x != nil {
		return x.RequestCount
	}
	return 0
}

func (x *ServiceHealth) GetErrorRate() float64 {
	if x != nil {
		return x.ErrorRate
	}
	return 0
}

type GetSystemHealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSystemHealthRequest) Reset() {
	*x = GetSystemHealthRequest{}
	mi := &file_proto_analytics_analytics_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSystemHealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSystemHealthRequest) ProtoMessage() {}

func (x *GetSystemHealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_analytics_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSystemHealthRequest.ProtoReflect.Descriptor instead.
func (*GetSystemHealthRequest) Descriptor() ([]byte, []int) {
	return file_proto_analytics_analytics_proto_rawDescGZIP(), []int{19}
}

type SystemHealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OverallStatus string                 `protobuf:"bytes,1,opt,name=overall_status,json=overallStatus,proto3" json:"overall_status,omitempty"`
	Services      []*ServiceHealth       `protobuf:"bytes,2,rep,name=services,proto3" json:"services,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemHealthResponse) Reset() {
	*x = SystemHealthResponse{}
	mi := &file_proto_analytics_analytics_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemHealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemHealthResponse) ProtoMessage() {}

func (x *SystemHealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_analytics_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemHealthResponse.ProtoReflect.Descriptor instead.
func (*SystemHealthResponse) Descriptor() ([]byte, []int) {
	return file_proto_analytics_analytics_proto_rawDescGZIP(), []int{20}
}

func (x *SystemHealthResponse) GetOverallStatus() string {
	if x != nil {
		return x.OverallStatus
	}
	return ""
}

func (x *SystemHealthResponse) GetServices() []*ServiceHealth {
	if x != nil {
		return x.Services
	}
	return nil
}

// 报表相关消息
type Report struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Period        string                 `protobuf:"bytes,4,opt,name=period,proto3" json:"period,omitempty"`
	Format        string                 `protobuf:"bytes,5,opt,name=format,proto3" json:"format,omitempty"`
	FileUrl       string                 `protobuf:"bytes,6,opt,name=file_url,json=fileUrl,proto3" json:"file_url,omitempty"`
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Report) Reset() {
	*x = Report{}
	mi := &file_proto_analytics_analytics_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Report) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Report) ProtoMessage() {}

func (x *Report) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_analytics_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Report.ProtoReflect.Descriptor instead.
func (*Report) Descriptor() ([]byte, []int) {
	return file_proto_analytics_analytics_proto_rawDescGZIP(), []int{21}
}

func (x *Report) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Report) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Report) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Report) GetPeriod() string {
	if x != nil {
		return x.Period
	}
	return ""
}

func (x *Report) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *Report) GetFileUrl() string {
	if x != nil {
		return x.FileUrl
	}
	return ""
}

func (x *Report) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Report) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type GenerateReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	MerchantId    string                 `protobuf:"bytes,3,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Format        string                 `protobuf:"bytes,6,opt,name=format,proto3" json:"format,omitempty"` // pdf, excel, csv
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateReportRequest) Reset() {
	*x = GenerateReportRequest{}
	mi := &file_proto_analytics_analytics_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateReportRequest) ProtoMessage() {}

func (x *GenerateReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_analytics_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateReportRequest.ProtoReflect.Descriptor instead.
func (*GenerateReportRequest) Descriptor() ([]byte, []int) {
	return file_proto_analytics_analytics_proto_rawDescGZIP(), []int{22}
}

func (x *GenerateReportRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GenerateReportRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *GenerateReportRequest) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *GenerateReportRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *GenerateReportRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *GenerateReportRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

type ReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Report        *Report                `protobuf:"bytes,1,opt,name=report,proto3" json:"report,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportResponse) Reset() {
	*x = ReportResponse{}
	mi := &file_proto_analytics_analytics_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportResponse) ProtoMessage() {}

func (x *ReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_analytics_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportResponse.ProtoReflect.Descriptor instead.
func (*ReportResponse) Descriptor() ([]byte, []int) {
	return file_proto_analytics_analytics_proto_rawDescGZIP(), []int{23}
}

func (x *ReportResponse) GetReport() *Report {
	if x != nil {
		return x.Report
	}
	return nil
}

type ListReportsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerchantId    string                 `protobuf:"bytes,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReportsRequest) Reset() {
	*x = ListReportsRequest{}
	mi := &file_proto_analytics_analytics_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReportsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReportsRequest) ProtoMessage() {}

func (x *ListReportsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_analytics_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReportsRequest.ProtoReflect.Descriptor instead.
func (*ListReportsRequest) Descriptor() ([]byte, []int) {
	return file_proto_analytics_analytics_proto_rawDescGZIP(), []int{24}
}

func (x *ListReportsRequest) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *ListReportsRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ListReportsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListReportsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListReportsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reports       []*Report              `protobuf:"bytes,1,rep,name=reports,proto3" json:"reports,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReportsResponse) Reset() {
	*x = ListReportsResponse{}
	mi := &file_proto_analytics_analytics_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReportsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReportsResponse) ProtoMessage() {}

func (x *ListReportsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_analytics_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReportsResponse.ProtoReflect.Descriptor instead.
func (*ListReportsResponse) Descriptor() ([]byte, []int) {
	return file_proto_analytics_analytics_proto_rawDescGZIP(), []int{25}
}

func (x *ListReportsResponse) GetReports() []*Report {
	if x != nil {
		return x.Reports
	}
	return nil
}

func (x *ListReportsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_proto_analytics_analytics_proto protoreflect.FileDescriptor

const file_proto_analytics_analytics_proto_rawDesc = "" +
	"\n" +
	"\x1fproto/analytics/analytics.proto\x12\tanalytics\x1a\x1fgoogle/protobuf/timestamp.proto\"\x98\x02\n" +
	"\fPaymentStats\x12\x1f\n" +
	"\vtotal_count\x18\x01 \x01(\x03R\n" +
	"totalCount\x12#\n" +
	"\rsuccess_count\x18\x02 \x01(\x03R\fsuccessCount\x12!\n" +
	"\ffailed_count\x18\x03 \x01(\x03R\vfailedCount\x12!\n" +
	"\ftotal_amount\x18\x04 \x01(\x03R\vtotalAmount\x12!\n" +
	"\fsuccess_rate\x18\x05 \x01(\x01R\vsuccessRate\x12%\n" +
	"\x0eaverage_amount\x18\x06 \x01(\x01R\raverageAmount\x12\x1a\n" +
	"\bcurrency\x18\a \x01(\tR\bcurrency\x12\x16\n" +
	"\x06period\x18\b \x01(\tR\x06period\"\xc7\x01\n" +
	"\x16GetPaymentStatsRequest\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\tR\n" +
	"merchantId\x129\n" +
	"\n" +
	"start_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\"E\n" +
	"\x14PaymentStatsResponse\x12-\n" +
	"\x05stats\x18\x01 \x01(\v2\x17.analytics.PaymentStatsR\x05stats\"N\n" +
	"\n" +
	"TrendPoint\x12\x12\n" +
	"\x04time\x18\x01 \x01(\tR\x04time\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\"\xce\x01\n" +
	"\x17GetPaymentTrendsRequest\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\tR\n" +
	"merchantId\x129\n" +
	"\n" +
	"start_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12 \n" +
	"\vgranularity\x18\x04 \x01(\tR\vgranularity\"F\n" +
	"\x15PaymentTrendsResponse\x12-\n" +
	"\x06trends\x18\x01 \x03(\v2\x15.analytics.TrendPointR\x06trends\"x\n" +
	"\vChannelStat\x12\x18\n" +
	"\achannel\x18\x01 \x01(\tR\achannel\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\x12!\n" +
	"\fsuccess_rate\x18\x04 \x01(\x01R\vsuccessRate\"\xab\x01\n" +
	"\x16GetChannelStatsRequest\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\tR\n" +
	"merchantId\x129\n" +
	"\n" +
	"start_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\"J\n" +
	"\x14ChannelStatsResponse\x122\n" +
	"\bchannels\x18\x01 \x03(\v2\x16.analytics.ChannelStatR\bchannels\"\xf3\x01\n" +
	"\rMerchantStats\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\tR\n" +
	"merchantId\x12#\n" +
	"\rmerchant_name\x18\x02 \x01(\tR\fmerchantName\x12-\n" +
	"\x12total_transactions\x18\x03 \x01(\x03R\x11totalTransactions\x12!\n" +
	"\ftotal_amount\x18\x04 \x01(\x03R\vtotalAmount\x12!\n" +
	"\factive_users\x18\x05 \x01(\x03R\vactiveUsers\x12'\n" +
	"\x0fconversion_rate\x18\x06 \x01(\x01R\x0econversionRate\"\xac\x01\n" +
	"\x17GetMerchantStatsRequest\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\tR\n" +
	"merchantId\x129\n" +
	"\n" +
	"start_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\"G\n" +
	"\x15MerchantStatsResponse\x12.\n" +
	"\x05stats\x18\x01 \x01(\v2\x18.analytics.MerchantStatsR\x05stats\"\xa3\x01\n" +
	"\vTopMerchant\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\tR\n" +
	"merchantId\x12#\n" +
	"\rmerchant_name\x18\x02 \x01(\tR\fmerchantName\x12!\n" +
	"\ftotal_amount\x18\x03 \x01(\x03R\vtotalAmount\x12+\n" +
	"\x11transaction_count\x18\x04 \x01(\x03R\x10transactionCount\"\xbb\x01\n" +
	"\x16GetTopMerchantsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x129\n" +
	"\n" +
	"start_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12\x19\n" +
	"\border_by\x18\x04 \x01(\tR\aorderBy\"L\n" +
	"\x14TopMerchantsResponse\x124\n" +
	"\tmerchants\x18\x01 \x03(\v2\x16.analytics.TopMerchantR\tmerchants\"\x8e\x02\n" +
	"\x0fRealtimeMetrics\x12'\n" +
	"\x0factive_sessions\x18\x01 \x01(\x03R\x0eactiveSessions\x12.\n" +
	"\x13requests_per_second\x18\x02 \x01(\x03R\x11requestsPerSecond\x12:\n" +
	"\x19successful_payments_count\x18\x03 \x01(\x03R\x17successfulPaymentsCount\x122\n" +
	"\x15failed_payments_count\x18\x04 \x01(\x03R\x13failedPaymentsCount\x122\n" +
	"\x15average_response_time\x18\x05 \x01(\x01R\x13averageResponseTime\":\n" +
	"\x19GetRealtimeMetricsRequest\x12\x1d\n" +
	"\n" +
	"time_range\x18\x01 \x01(\tR\ttimeRange\"O\n" +
	"\x17RealtimeMetricsResponse\x124\n" +
	"\ametrics\x18\x01 \x01(\v2\x1a.analytics.RealtimeMetricsR\ametrics\"\xce\x01\n" +
	"\rServiceHealth\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1b\n" +
	"\tcpu_usage\x18\x03 \x01(\x01R\bcpuUsage\x12!\n" +
	"\fmemory_usage\x18\x04 \x01(\x01R\vmemoryUsage\x12#\n" +
	"\rrequest_count\x18\x05 \x01(\x03R\frequestCount\x12\x1d\n" +
	"\n" +
	"error_rate\x18\x06 \x01(\x01R\terrorRate\"\x18\n" +
	"\x16GetSystemHealthRequest\"s\n" +
	"\x14SystemHealthResponse\x12%\n" +
	"\x0eoverall_status\x18\x01 \x01(\tR\roverallStatus\x124\n" +
	"\bservices\x18\x02 \x03(\v2\x18.analytics.ServiceHealthR\bservices\"\xde\x01\n" +
	"\x06Report\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x16\n" +
	"\x06period\x18\x04 \x01(\tR\x06period\x12\x16\n" +
	"\x06format\x18\x05 \x01(\tR\x06format\x12\x19\n" +
	"\bfile_url\x18\x06 \x01(\tR\afileUrl\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xea\x01\n" +
	"\x15GenerateReportRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1f\n" +
	"\vmerchant_id\x18\x03 \x01(\tR\n" +
	"merchantId\x129\n" +
	"\n" +
	"start_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12\x16\n" +
	"\x06format\x18\x06 \x01(\tR\x06format\";\n" +
	"\x0eReportResponse\x12)\n" +
	"\x06report\x18\x01 \x01(\v2\x11.analytics.ReportR\x06report\"z\n" +
	"\x12ListReportsRequest\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\tR\n" +
	"merchantId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"X\n" +
	"\x13ListReportsResponse\x12+\n" +
	"\areports\x18\x01 \x03(\v2\x11.analytics.ReportR\areports\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total2\x9f\x06\n" +
	"\x10AnalyticsService\x12U\n" +
	"\x0fGetPaymentStats\x12!.analytics.GetPaymentStatsRequest\x1a\x1f.analytics.PaymentStatsResponse\x12X\n" +
	"\x10GetPaymentTrends\x12\".analytics.GetPaymentTrendsRequest\x1a .analytics.PaymentTrendsResponse\x12U\n" +
	"\x0fGetChannelStats\x12!.analytics.GetChannelStatsRequest\x1a\x1f.analytics.ChannelStatsResponse\x12X\n" +
	"\x10GetMerchantStats\x12\".analytics.GetMerchantStatsRequest\x1a .analytics.MerchantStatsResponse\x12U\n" +
	"\x0fGetTopMerchants\x12!.analytics.GetTopMerchantsRequest\x1a\x1f.analytics.TopMerchantsResponse\x12^\n" +
	"\x12GetRealtimeMetrics\x12$.analytics.GetRealtimeMetricsRequest\x1a\".analytics.RealtimeMetricsResponse\x12U\n" +
	"\x0fGetSystemHealth\x12!.analytics.GetSystemHealthRequest\x1a\x1f.analytics.SystemHealthResponse\x12M\n" +
	"\x0eGenerateReport\x12 .analytics.GenerateReportRequest\x1a\x19.analytics.ReportResponse\x12L\n" +
	"\vListReports\x12\x1d.analytics.ListReportsRequest\x1a\x1e.analytics.ListReportsResponseB7Z5github.com/payment-platform/proto/analytics;analyticsb\x06proto3"

var (
	file_proto_analytics_analytics_proto_rawDescOnce sync.Once
	file_proto_analytics_analytics_proto_rawDescData []byte
)

func file_proto_analytics_analytics_proto_rawDescGZIP() []byte {
	file_proto_analytics_analytics_proto_rawDescOnce.Do(func() {
		file_proto_analytics_analytics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_analytics_analytics_proto_rawDesc), len(file_proto_analytics_analytics_proto_rawDesc)))
	})
	return file_proto_analytics_analytics_proto_rawDescData
}

var file_proto_analytics_analytics_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_proto_analytics_analytics_proto_goTypes = []any{
	(*PaymentStats)(nil),              // 0: analytics.PaymentStats
	(*GetPaymentStatsRequest)(nil),    // 1: analytics.GetPaymentStatsRequest
	(*PaymentStatsResponse)(nil),      // 2: analytics.PaymentStatsResponse
	(*TrendPoint)(nil),                // 3: analytics.TrendPoint
	(*GetPaymentTrendsRequest)(nil),   // 4: analytics.GetPaymentTrendsRequest
	(*PaymentTrendsResponse)(nil),     // 5: analytics.PaymentTrendsResponse
	(*ChannelStat)(nil),               // 6: analytics.ChannelStat
	(*GetChannelStatsRequest)(nil),    // 7: analytics.GetChannelStatsRequest
	(*ChannelStatsResponse)(nil),      // 8: analytics.ChannelStatsResponse
	(*MerchantStats)(nil),             // 9: analytics.MerchantStats
	(*GetMerchantStatsRequest)(nil),   // 10: analytics.GetMerchantStatsRequest
	(*MerchantStatsResponse)(nil),     // 11: analytics.MerchantStatsResponse
	(*TopMerchant)(nil),               // 12: analytics.TopMerchant
	(*GetTopMerchantsRequest)(nil),    // 13: analytics.GetTopMerchantsRequest
	(*TopMerchantsResponse)(nil),      // 14: analytics.TopMerchantsResponse
	(*RealtimeMetrics)(nil),           // 15: analytics.RealtimeMetrics
	(*GetRealtimeMetricsRequest)(nil), // 16: analytics.GetRealtimeMetricsRequest
	(*RealtimeMetricsResponse)(nil),   // 17: analytics.RealtimeMetricsResponse
	(*ServiceHealth)(nil),             // 18: analytics.ServiceHealth
	(*GetSystemHealthRequest)(nil),    // 19: analytics.GetSystemHealthRequest
	(*SystemHealthResponse)(nil),      // 20: analytics.SystemHealthResponse
	(*Report)(nil),                    // 21: analytics.Report
	(*GenerateReportRequest)(nil),     // 22: analytics.GenerateReportRequest
	(*ReportResponse)(nil),            // 23: analytics.ReportResponse
	(*ListReportsRequest)(nil),        // 24: analytics.ListReportsRequest
	(*ListReportsResponse)(nil),       // 25: analytics.ListReportsResponse
	(*timestamppb.Timestamp)(nil),     // 26: google.protobuf.Timestamp
}
var file_proto_analytics_analytics_proto_depIdxs = []int32{
	26, // 0: analytics.GetPaymentStatsRequest.start_time:type_name -> google.protobuf.Timestamp
	26, // 1: analytics.GetPaymentStatsRequest.end_time:type_name -> google.protobuf.Timestamp
	0,  // 2: analytics.PaymentStatsResponse.stats:type_name -> analytics.PaymentStats
	26, // 3: analytics.GetPaymentTrendsRequest.start_time:type_name -> google.protobuf.Timestamp
	26, // 4: analytics.GetPaymentTrendsRequest.end_time:type_name -> google.protobuf.Timestamp
	3,  // 5: analytics.PaymentTrendsResponse.trends:type_name -> analytics.TrendPoint
	26, // 6: analytics.GetChannelStatsRequest.start_time:type_name -> google.protobuf.Timestamp
	26, // 7: analytics.GetChannelStatsRequest.end_time:type_name -> google.protobuf.Timestamp
	6,  // 8: analytics.ChannelStatsResponse.channels:type_name -> analytics.ChannelStat
	26, // 9: analytics.GetMerchantStatsRequest.start_time:type_name -> google.protobuf.Timestamp
	26, // 10: analytics.GetMerchantStatsRequest.end_time:type_name -> google.protobuf.Timestamp
	9,  // 11: analytics.MerchantStatsResponse.stats:type_name -> analytics.MerchantStats
	26, // 12: analytics.GetTopMerchantsRequest.start_time:type_name -> google.protobuf.Timestamp
	26, // 13: analytics.GetTopMerchantsRequest.end_time:type_name -> google.protobuf.Timestamp
	12, // 14: analytics.TopMerchantsResponse.merchants:type_name -> analytics.TopMerchant
	15, // 15: analytics.RealtimeMetricsResponse.metrics:type_name -> analytics.RealtimeMetrics
	18, // 16: analytics.SystemHealthResponse.services:type_name -> analytics.ServiceHealth
	26, // 17: analytics.Report.created_at:type_name -> google.protobuf.Timestamp
	26, // 18: analytics.GenerateReportRequest.start_time:type_name -> google.protobuf.Timestamp
	26, // 19: analytics.GenerateReportRequest.end_time:type_name -> google.protobuf.Timestamp
	21, // 20: analytics.ReportResponse.report:type_name -> analytics.Report
	21, // 21: analytics.ListReportsResponse.reports:type_name -> analytics.Report
	1,  // 22: analytics.AnalyticsService.GetPaymentStats:input_type -> analytics.GetPaymentStatsRequest
	4,  // 23: analytics.AnalyticsService.GetPaymentTrends:input_type -> analytics.GetPaymentTrendsRequest
	7,  // 24: analytics.AnalyticsService.GetChannelStats:input_type -> analytics.GetChannelStatsRequest
	10, // 25: analytics.AnalyticsService.GetMerchantStats:input_type -> analytics.GetMerchantStatsRequest
	13, // 26: analytics.AnalyticsService.GetTopMerchants:input_type -> analytics.GetTopMerchantsRequest
	16, // 27: analytics.AnalyticsService.GetRealtimeMetrics:input_type -> analytics.GetRealtimeMetricsRequest
	19, // 28: analytics.AnalyticsService.GetSystemHealth:input_type -> analytics.GetSystemHealthRequest
	22, // 29: analytics.AnalyticsService.GenerateReport:input_type -> analytics.GenerateReportRequest
	24, // 30: analytics.AnalyticsService.ListReports:input_type -> analytics.ListReportsRequest
	2,  // 31: analytics.AnalyticsService.GetPaymentStats:output_type -> analytics.PaymentStatsResponse
	5,  // 32: analytics.AnalyticsService.GetPaymentTrends:output_type -> analytics.PaymentTrendsResponse
	8,  // 33: analytics.AnalyticsService.GetChannelStats:output_type -> analytics.ChannelStatsResponse
	11, // 34: analytics.AnalyticsService.GetMerchantStats:output_type -> analytics.MerchantStatsResponse
	14, // 35: analytics.AnalyticsService.GetTopMerchants:output_type -> analytics.TopMerchantsResponse
	17, // 36: analytics.AnalyticsService.GetRealtimeMetrics:output_type -> analytics.RealtimeMetricsResponse
	20, // 37: analytics.AnalyticsService.GetSystemHealth:output_type -> analytics.SystemHealthResponse
	23, // 38: analytics.AnalyticsService.GenerateReport:output_type -> analytics.ReportResponse
	25, // 39: analytics.AnalyticsService.ListReports:output_type -> analytics.ListReportsResponse
	31, // [31:40] is the sub-list for method output_type
	22, // [22:31] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_proto_analytics_analytics_proto_init() }
func file_proto_analytics_analytics_proto_init() {
	if File_proto_analytics_analytics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_analytics_analytics_proto_rawDesc), len(file_proto_analytics_analytics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_analytics_analytics_proto_goTypes,
		DependencyIndexes: file_proto_analytics_analytics_proto_depIdxs,
		MessageInfos:      file_proto_analytics_analytics_proto_msgTypes,
	}.Build()
	File_proto_analytics_analytics_proto = out.File
	file_proto_analytics_analytics_proto_goTypes = nil
	file_proto_analytics_analytics_proto_depIdxs = nil
}
