basePath: /api/v1
definitions:
  internal_handler.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  internal_handler.UpdateKYCStatusRequest:
    properties:
      kyc_status:
        type: string
    required:
    - kyc_status
    type: object
  internal_handler.UpdatePasswordRequest:
    properties:
      password_hash:
        type: string
    required:
    - password_hash
    type: object
  internal_handler.UpdateStatusRequest:
    properties:
      status:
        type: string
    required:
    - status
    type: object
  payment-platform_merchant-service_internal_service.CreateMerchantInput:
    properties:
      businessType:
        type: string
      companyName:
        type: string
      country:
        type: string
      email:
        type: string
      name:
        type: string
      password:
        type: string
      phone:
        type: string
      website:
        type: string
    type: object
  payment-platform_merchant-service_internal_service.RegisterMerchantInput:
    properties:
      businessType:
        type: string
      companyName:
        type: string
      country:
        type: string
      email:
        type: string
      name:
        type: string
      password:
        type: string
      website:
        type: string
    type: object
  payment-platform_merchant-service_internal_service.UpdateMerchantInput:
    properties:
      businessType:
        type: string
      companyName:
        type: string
      country:
        type: string
      isTestMode:
        type: boolean
      metadata:
        type: string
      name:
        type: string
      phone:
        type: string
      website:
        type: string
    type: object
host: localhost:40002
info:
  contact:
    email: support@payment-platform.com
    name: API Support
  description: 支付平台商户管理服务API文档（Phase 10 清理后）
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Merchant Service API
  version: "1.0"
paths:
  /api/v1/dashboard:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: 获取Dashboard概览
      tags:
      - Dashboard
  /api/v1/dashboard/balance:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: 获取余额信息
      tags:
      - Dashboard
  /api/v1/dashboard/transaction-summary:
    get:
      parameters:
      - description: 开始日期 YYYY-MM-DD
        in: query
        name: start_date
        type: string
      - description: 结束日期 YYYY-MM-DD
        in: query
        name: end_date
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: 获取交易汇总
      tags:
      - Dashboard
  /api/v1/merchant:
    get:
      parameters:
      - default: 1
        description: 页码
        in: query
        name: page
        type: integer
      - default: 20
        description: 每页数量
        in: query
        name: page_size
        type: integer
      - description: 状态筛选
        in: query
        name: status
        type: string
      - description: KYC状态筛选
        in: query
        name: kyc_status
        type: string
      - description: 关键词搜索
        in: query
        name: keyword
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: 获取商户列表
      tags:
      - Merchant
    post:
      consumes:
      - application/json
      parameters:
      - description: 商户信息
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/payment-platform_merchant-service_internal_service.CreateMerchantInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: 创建商户
      tags:
      - Merchant
  /api/v1/merchant/{id}:
    delete:
      parameters:
      - description: 商户ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: 删除商户
      tags:
      - Merchant
    get:
      parameters:
      - description: 商户ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: 获取商户详情
      tags:
      - Merchant
    put:
      consumes:
      - application/json
      parameters:
      - description: 商户ID
        in: path
        name: id
        required: true
        type: string
      - description: 更新信息
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/payment-platform_merchant-service_internal_service.UpdateMerchantInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: 更新商户信息
      tags:
      - Merchant
  /api/v1/merchant/{id}/kyc-status:
    put:
      consumes:
      - application/json
      parameters:
      - description: 商户ID
        in: path
        name: id
        required: true
        type: string
      - description: KYC状态信息
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/internal_handler.UpdateKYCStatusRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: 更新KYC状态
      tags:
      - Merchant
  /api/v1/merchant/{id}/status:
    put:
      consumes:
      - application/json
      parameters:
      - description: 商户ID
        in: path
        name: id
        required: true
        type: string
      - description: 状态信息
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/internal_handler.UpdateStatusRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: 更新商户状态
      tags:
      - Merchant
  /api/v1/merchant/balance:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: 获取商户余额
      tags:
      - Merchant
  /api/v1/merchant/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: 登录信息
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/internal_handler.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: 商户登录
      tags:
      - Merchant
  /api/v1/merchant/payments:
    get:
      parameters:
      - default: 1
        description: 页码
        in: query
        name: page
        type: integer
      - default: 10
        description: 每页数量
        in: query
        name: page_size
        type: integer
      - description: 支付状态
        in: query
        name: status
        type: string
      - description: 支付渠道
        in: query
        name: channel
        type: string
      - description: 开始时间
        in: query
        name: start_time
        type: string
      - description: 结束时间
        in: query
        name: end_time
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: 获取当前商户的支付列表
      tags:
      - Payment
  /api/v1/merchant/profile:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: 获取当前商户信息
      tags:
      - Merchant
    put:
      consumes:
      - application/json
      parameters:
      - description: 更新信息
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/payment-platform_merchant-service_internal_service.UpdateMerchantInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: 更新当前商户信息
      tags:
      - Merchant
  /api/v1/merchant/refunds:
    get:
      parameters:
      - default: 1
        description: 页码
        in: query
        name: page
        type: integer
      - default: 10
        description: 每页数量
        in: query
        name: page_size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: 获取当前商户的退款列表
      tags:
      - Payment
  /api/v1/merchant/register:
    post:
      consumes:
      - application/json
      parameters:
      - description: 注册信息
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/payment-platform_merchant-service_internal_service.RegisterMerchantInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: 商户注册
      tags:
      - Merchant
  /api/v1/merchant/stats:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: 获取商户统计
      tags:
      - Merchant
  /api/v1/merchants/{id}/password:
    put:
      consumes:
      - application/json
      parameters:
      - description: 商户ID
        in: path
        name: id
        required: true
        type: string
      - description: 密码哈希
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/internal_handler.UpdatePasswordRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: 更新商户密码
      tags:
      - Merchant
  /api/v1/merchants/{id}/with-password:
    get:
      parameters:
      - description: 商户ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: 获取带密码的商户信息
      tags:
      - Merchant
securityDefinitions:
  BearerAuth:
    description: Type "Bearer" followed by a space and JWT token.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
