// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.25.1
// source: proto/risk/risk.proto

package risk

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 风控检查相关消息
type CheckPaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerchantId    string                 `protobuf:"bytes,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	RelatedId     string                 `protobuf:"bytes,2,opt,name=related_id,json=relatedId,proto3" json:"related_id,omitempty"`
	RelatedType   string                 `protobuf:"bytes,3,opt,name=related_type,json=relatedType,proto3" json:"related_type,omitempty"`
	Amount        int64                  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency      string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	PayerIp       string                 `protobuf:"bytes,6,opt,name=payer_ip,json=payerIp,proto3" json:"payer_ip,omitempty"`
	PayerEmail    string                 `protobuf:"bytes,7,opt,name=payer_email,json=payerEmail,proto3" json:"payer_email,omitempty"`
	PayerPhone    string                 `protobuf:"bytes,8,opt,name=payer_phone,json=payerPhone,proto3" json:"payer_phone,omitempty"`
	DeviceId      string                 `protobuf:"bytes,9,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	PaymentMethod string                 `protobuf:"bytes,10,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	Extra         *structpb.Struct       `protobuf:"bytes,11,opt,name=extra,proto3" json:"extra,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckPaymentRequest) Reset() {
	*x = CheckPaymentRequest{}
	mi := &file_proto_risk_risk_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPaymentRequest) ProtoMessage() {}

func (x *CheckPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_risk_risk_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPaymentRequest.ProtoReflect.Descriptor instead.
func (*CheckPaymentRequest) Descriptor() ([]byte, []int) {
	return file_proto_risk_risk_proto_rawDescGZIP(), []int{0}
}

func (x *CheckPaymentRequest) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *CheckPaymentRequest) GetRelatedId() string {
	if x != nil {
		return x.RelatedId
	}
	return ""
}

func (x *CheckPaymentRequest) GetRelatedType() string {
	if x != nil {
		return x.RelatedType
	}
	return ""
}

func (x *CheckPaymentRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CheckPaymentRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CheckPaymentRequest) GetPayerIp() string {
	if x != nil {
		return x.PayerIp
	}
	return ""
}

func (x *CheckPaymentRequest) GetPayerEmail() string {
	if x != nil {
		return x.PayerEmail
	}
	return ""
}

func (x *CheckPaymentRequest) GetPayerPhone() string {
	if x != nil {
		return x.PayerPhone
	}
	return ""
}

func (x *CheckPaymentRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *CheckPaymentRequest) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *CheckPaymentRequest) GetExtra() *structpb.Struct {
	if x != nil {
		return x.Extra
	}
	return nil
}

type CheckPaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Decision      string                 `protobuf:"bytes,1,opt,name=decision,proto3" json:"decision,omitempty"` // accept, reject, review
	Score         int32                  `protobuf:"varint,2,opt,name=score,proto3" json:"score,omitempty"`
	Reasons       []string               `protobuf:"bytes,3,rep,name=reasons,proto3" json:"reasons,omitempty"`
	MatchedRules  []string               `protobuf:"bytes,4,rep,name=matched_rules,json=matchedRules,proto3" json:"matched_rules,omitempty"`
	CheckId       string                 `protobuf:"bytes,5,opt,name=check_id,json=checkId,proto3" json:"check_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckPaymentResponse) Reset() {
	*x = CheckPaymentResponse{}
	mi := &file_proto_risk_risk_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckPaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPaymentResponse) ProtoMessage() {}

func (x *CheckPaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_risk_risk_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPaymentResponse.ProtoReflect.Descriptor instead.
func (*CheckPaymentResponse) Descriptor() ([]byte, []int) {
	return file_proto_risk_risk_proto_rawDescGZIP(), []int{1}
}

func (x *CheckPaymentResponse) GetDecision() string {
	if x != nil {
		return x.Decision
	}
	return ""
}

func (x *CheckPaymentResponse) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *CheckPaymentResponse) GetReasons() []string {
	if x != nil {
		return x.Reasons
	}
	return nil
}

func (x *CheckPaymentResponse) GetMatchedRules() []string {
	if x != nil {
		return x.MatchedRules
	}
	return nil
}

func (x *CheckPaymentResponse) GetCheckId() string {
	if x != nil {
		return x.CheckId
	}
	return ""
}

type ReportPaymentResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CheckId       string                 `protobuf:"bytes,1,opt,name=check_id,json=checkId,proto3" json:"check_id,omitempty"`
	Result        string                 `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"` // success, failed
	ErrorCode     string                 `protobuf:"bytes,3,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportPaymentResultRequest) Reset() {
	*x = ReportPaymentResultRequest{}
	mi := &file_proto_risk_risk_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportPaymentResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportPaymentResultRequest) ProtoMessage() {}

func (x *ReportPaymentResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_risk_risk_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportPaymentResultRequest.ProtoReflect.Descriptor instead.
func (*ReportPaymentResultRequest) Descriptor() ([]byte, []int) {
	return file_proto_risk_risk_proto_rawDescGZIP(), []int{2}
}

func (x *ReportPaymentResultRequest) GetCheckId() string {
	if x != nil {
		return x.CheckId
	}
	return ""
}

func (x *ReportPaymentResultRequest) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *ReportPaymentResultRequest) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *ReportPaymentResultRequest) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type ReportPaymentResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportPaymentResultResponse) Reset() {
	*x = ReportPaymentResultResponse{}
	mi := &file_proto_risk_risk_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportPaymentResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportPaymentResultResponse) ProtoMessage() {}

func (x *ReportPaymentResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_risk_risk_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportPaymentResultResponse.ProtoReflect.Descriptor instead.
func (*ReportPaymentResultResponse) Descriptor() ([]byte, []int) {
	return file_proto_risk_risk_proto_rawDescGZIP(), []int{3}
}

func (x *ReportPaymentResultResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// 规则管理相关消息
type RiskRule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RuleName      string                 `protobuf:"bytes,2,opt,name=rule_name,json=ruleName,proto3" json:"rule_name,omitempty"`
	RuleType      string                 `protobuf:"bytes,3,opt,name=rule_type,json=ruleType,proto3" json:"rule_type,omitempty"`
	Conditions    *structpb.Struct       `protobuf:"bytes,4,opt,name=conditions,proto3" json:"conditions,omitempty"`
	Actions       *structpb.Struct       `protobuf:"bytes,5,opt,name=actions,proto3" json:"actions,omitempty"`
	Priority      int32                  `protobuf:"varint,6,opt,name=priority,proto3" json:"priority,omitempty"`
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	Description   string                 `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RiskRule) Reset() {
	*x = RiskRule{}
	mi := &file_proto_risk_risk_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RiskRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RiskRule) ProtoMessage() {}

func (x *RiskRule) ProtoReflect() protoreflect.Message {
	mi := &file_proto_risk_risk_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RiskRule.ProtoReflect.Descriptor instead.
func (*RiskRule) Descriptor() ([]byte, []int) {
	return file_proto_risk_risk_proto_rawDescGZIP(), []int{4}
}

func (x *RiskRule) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RiskRule) GetRuleName() string {
	if x != nil {
		return x.RuleName
	}
	return ""
}

func (x *RiskRule) GetRuleType() string {
	if x != nil {
		return x.RuleType
	}
	return ""
}

func (x *RiskRule) GetConditions() *structpb.Struct {
	if x != nil {
		return x.Conditions
	}
	return nil
}

func (x *RiskRule) GetActions() *structpb.Struct {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *RiskRule) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *RiskRule) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RiskRule) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RiskRule) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *RiskRule) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateRuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RuleName      string                 `protobuf:"bytes,1,opt,name=rule_name,json=ruleName,proto3" json:"rule_name,omitempty"`
	RuleType      string                 `protobuf:"bytes,2,opt,name=rule_type,json=ruleType,proto3" json:"rule_type,omitempty"`
	Conditions    *structpb.Struct       `protobuf:"bytes,3,opt,name=conditions,proto3" json:"conditions,omitempty"`
	Actions       *structpb.Struct       `protobuf:"bytes,4,opt,name=actions,proto3" json:"actions,omitempty"`
	Priority      int32                  `protobuf:"varint,5,opt,name=priority,proto3" json:"priority,omitempty"`
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRuleRequest) Reset() {
	*x = CreateRuleRequest{}
	mi := &file_proto_risk_risk_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRuleRequest) ProtoMessage() {}

func (x *CreateRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_risk_risk_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRuleRequest.ProtoReflect.Descriptor instead.
func (*CreateRuleRequest) Descriptor() ([]byte, []int) {
	return file_proto_risk_risk_proto_rawDescGZIP(), []int{5}
}

func (x *CreateRuleRequest) GetRuleName() string {
	if x != nil {
		return x.RuleName
	}
	return ""
}

func (x *CreateRuleRequest) GetRuleType() string {
	if x != nil {
		return x.RuleType
	}
	return ""
}

func (x *CreateRuleRequest) GetConditions() *structpb.Struct {
	if x != nil {
		return x.Conditions
	}
	return nil
}

func (x *CreateRuleRequest) GetActions() *structpb.Struct {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *CreateRuleRequest) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *CreateRuleRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type UpdateRuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RuleName      string                 `protobuf:"bytes,2,opt,name=rule_name,json=ruleName,proto3" json:"rule_name,omitempty"`
	Conditions    *structpb.Struct       `protobuf:"bytes,3,opt,name=conditions,proto3" json:"conditions,omitempty"`
	Actions       *structpb.Struct       `protobuf:"bytes,4,opt,name=actions,proto3" json:"actions,omitempty"`
	Priority      int32                  `protobuf:"varint,5,opt,name=priority,proto3" json:"priority,omitempty"`
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRuleRequest) Reset() {
	*x = UpdateRuleRequest{}
	mi := &file_proto_risk_risk_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRuleRequest) ProtoMessage() {}

func (x *UpdateRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_risk_risk_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRuleRequest.ProtoReflect.Descriptor instead.
func (*UpdateRuleRequest) Descriptor() ([]byte, []int) {
	return file_proto_risk_risk_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateRuleRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateRuleRequest) GetRuleName() string {
	if x != nil {
		return x.RuleName
	}
	return ""
}

func (x *UpdateRuleRequest) GetConditions() *structpb.Struct {
	if x != nil {
		return x.Conditions
	}
	return nil
}

func (x *UpdateRuleRequest) GetActions() *structpb.Struct {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *UpdateRuleRequest) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *UpdateRuleRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type GetRuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRuleRequest) Reset() {
	*x = GetRuleRequest{}
	mi := &file_proto_risk_risk_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRuleRequest) ProtoMessage() {}

func (x *GetRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_risk_risk_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRuleRequest.ProtoReflect.Descriptor instead.
func (*GetRuleRequest) Descriptor() ([]byte, []int) {
	return file_proto_risk_risk_proto_rawDescGZIP(), []int{7}
}

func (x *GetRuleRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListRulesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	RuleType      string                 `protobuf:"bytes,3,opt,name=rule_type,json=ruleType,proto3" json:"rule_type,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRulesRequest) Reset() {
	*x = ListRulesRequest{}
	mi := &file_proto_risk_risk_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRulesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRulesRequest) ProtoMessage() {}

func (x *ListRulesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_risk_risk_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRulesRequest.ProtoReflect.Descriptor instead.
func (*ListRulesRequest) Descriptor() ([]byte, []int) {
	return file_proto_risk_risk_proto_rawDescGZIP(), []int{8}
}

func (x *ListRulesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListRulesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListRulesRequest) GetRuleType() string {
	if x != nil {
		return x.RuleType
	}
	return ""
}

func (x *ListRulesRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ListRulesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rules         []*RiskRule            `protobuf:"bytes,1,rep,name=rules,proto3" json:"rules,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRulesResponse) Reset() {
	*x = ListRulesResponse{}
	mi := &file_proto_risk_risk_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRulesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRulesResponse) ProtoMessage() {}

func (x *ListRulesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_risk_risk_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRulesResponse.ProtoReflect.Descriptor instead.
func (*ListRulesResponse) Descriptor() ([]byte, []int) {
	return file_proto_risk_risk_proto_rawDescGZIP(), []int{9}
}

func (x *ListRulesResponse) GetRules() []*RiskRule {
	if x != nil {
		return x.Rules
	}
	return nil
}

func (x *ListRulesResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type DeleteRuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRuleRequest) Reset() {
	*x = DeleteRuleRequest{}
	mi := &file_proto_risk_risk_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRuleRequest) ProtoMessage() {}

func (x *DeleteRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_risk_risk_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRuleRequest.ProtoReflect.Descriptor instead.
func (*DeleteRuleRequest) Descriptor() ([]byte, []int) {
	return file_proto_risk_risk_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteRuleRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteRuleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRuleResponse) Reset() {
	*x = DeleteRuleResponse{}
	mi := &file_proto_risk_risk_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRuleResponse) ProtoMessage() {}

func (x *DeleteRuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_risk_risk_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRuleResponse.ProtoReflect.Descriptor instead.
func (*DeleteRuleResponse) Descriptor() ([]byte, []int) {
	return file_proto_risk_risk_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteRuleResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type EnableRuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnableRuleRequest) Reset() {
	*x = EnableRuleRequest{}
	mi := &file_proto_risk_risk_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnableRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableRuleRequest) ProtoMessage() {}

func (x *EnableRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_risk_risk_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableRuleRequest.ProtoReflect.Descriptor instead.
func (*EnableRuleRequest) Descriptor() ([]byte, []int) {
	return file_proto_risk_risk_proto_rawDescGZIP(), []int{12}
}

func (x *EnableRuleRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DisableRuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisableRuleRequest) Reset() {
	*x = DisableRuleRequest{}
	mi := &file_proto_risk_risk_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisableRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableRuleRequest) ProtoMessage() {}

func (x *DisableRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_risk_risk_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableRuleRequest.ProtoReflect.Descriptor instead.
func (*DisableRuleRequest) Descriptor() ([]byte, []int) {
	return file_proto_risk_risk_proto_rawDescGZIP(), []int{13}
}

func (x *DisableRuleRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RuleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rule          *RiskRule              `protobuf:"bytes,1,opt,name=rule,proto3" json:"rule,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuleResponse) Reset() {
	*x = RuleResponse{}
	mi := &file_proto_risk_risk_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleResponse) ProtoMessage() {}

func (x *RuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_risk_risk_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuleResponse.ProtoReflect.Descriptor instead.
func (*RuleResponse) Descriptor() ([]byte, []int) {
	return file_proto_risk_risk_proto_rawDescGZIP(), []int{14}
}

func (x *RuleResponse) GetRule() *RiskRule {
	if x != nil {
		return x.Rule
	}
	return nil
}

// 检查记录相关消息
type RiskCheck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MerchantId    string                 `protobuf:"bytes,2,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	RelatedId     string                 `protobuf:"bytes,3,opt,name=related_id,json=relatedId,proto3" json:"related_id,omitempty"`
	RelatedType   string                 `protobuf:"bytes,4,opt,name=related_type,json=relatedType,proto3" json:"related_type,omitempty"`
	Amount        int64                  `protobuf:"varint,5,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency      string                 `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency,omitempty"`
	Decision      string                 `protobuf:"bytes,7,opt,name=decision,proto3" json:"decision,omitempty"`
	Score         int32                  `protobuf:"varint,8,opt,name=score,proto3" json:"score,omitempty"`
	Reasons       []string               `protobuf:"bytes,9,rep,name=reasons,proto3" json:"reasons,omitempty"`
	Result        string                 `protobuf:"bytes,10,opt,name=result,proto3" json:"result,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RiskCheck) Reset() {
	*x = RiskCheck{}
	mi := &file_proto_risk_risk_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RiskCheck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RiskCheck) ProtoMessage() {}

func (x *RiskCheck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_risk_risk_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RiskCheck.ProtoReflect.Descriptor instead.
func (*RiskCheck) Descriptor() ([]byte, []int) {
	return file_proto_risk_risk_proto_rawDescGZIP(), []int{15}
}

func (x *RiskCheck) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RiskCheck) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *RiskCheck) GetRelatedId() string {
	if x != nil {
		return x.RelatedId
	}
	return ""
}

func (x *RiskCheck) GetRelatedType() string {
	if x != nil {
		return x.RelatedType
	}
	return ""
}

func (x *RiskCheck) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *RiskCheck) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *RiskCheck) GetDecision() string {
	if x != nil {
		return x.Decision
	}
	return ""
}

func (x *RiskCheck) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *RiskCheck) GetReasons() []string {
	if x != nil {
		return x.Reasons
	}
	return nil
}

func (x *RiskCheck) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *RiskCheck) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type GetCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCheckRequest) Reset() {
	*x = GetCheckRequest{}
	mi := &file_proto_risk_risk_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCheckRequest) ProtoMessage() {}

func (x *GetCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_risk_risk_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCheckRequest.ProtoReflect.Descriptor instead.
func (*GetCheckRequest) Descriptor() ([]byte, []int) {
	return file_proto_risk_risk_proto_rawDescGZIP(), []int{16}
}

func (x *GetCheckRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Check         *RiskCheck             `protobuf:"bytes,1,opt,name=check,proto3" json:"check,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckResponse) Reset() {
	*x = CheckResponse{}
	mi := &file_proto_risk_risk_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckResponse) ProtoMessage() {}

func (x *CheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_risk_risk_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckResponse.ProtoReflect.Descriptor instead.
func (*CheckResponse) Descriptor() ([]byte, []int) {
	return file_proto_risk_risk_proto_rawDescGZIP(), []int{17}
}

func (x *CheckResponse) GetCheck() *RiskCheck {
	if x != nil {
		return x.Check
	}
	return nil
}

type ListChecksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerchantId    string                 `protobuf:"bytes,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	RelatedId     string                 `protobuf:"bytes,2,opt,name=related_id,json=relatedId,proto3" json:"related_id,omitempty"`
	Decision      string                 `protobuf:"bytes,3,opt,name=decision,proto3" json:"decision,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Page          int32                  `protobuf:"varint,6,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,7,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChecksRequest) Reset() {
	*x = ListChecksRequest{}
	mi := &file_proto_risk_risk_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChecksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChecksRequest) ProtoMessage() {}

func (x *ListChecksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_risk_risk_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChecksRequest.ProtoReflect.Descriptor instead.
func (*ListChecksRequest) Descriptor() ([]byte, []int) {
	return file_proto_risk_risk_proto_rawDescGZIP(), []int{18}
}

func (x *ListChecksRequest) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *ListChecksRequest) GetRelatedId() string {
	if x != nil {
		return x.RelatedId
	}
	return ""
}

func (x *ListChecksRequest) GetDecision() string {
	if x != nil {
		return x.Decision
	}
	return ""
}

func (x *ListChecksRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *ListChecksRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *ListChecksRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListChecksRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListChecksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Checks        []*RiskCheck           `protobuf:"bytes,1,rep,name=checks,proto3" json:"checks,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChecksResponse) Reset() {
	*x = ListChecksResponse{}
	mi := &file_proto_risk_risk_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChecksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChecksResponse) ProtoMessage() {}

func (x *ListChecksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_risk_risk_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChecksResponse.ProtoReflect.Descriptor instead.
func (*ListChecksResponse) Descriptor() ([]byte, []int) {
	return file_proto_risk_risk_proto_rawDescGZIP(), []int{19}
}

func (x *ListChecksResponse) GetChecks() []*RiskCheck {
	if x != nil {
		return x.Checks
	}
	return nil
}

func (x *ListChecksResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

// 黑名单相关消息
type Blacklist struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	EntityType    string                 `protobuf:"bytes,2,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"`
	EntityValue   string                 `protobuf:"bytes,3,opt,name=entity_value,json=entityValue,proto3" json:"entity_value,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	AddedBy       string                 `protobuf:"bytes,5,opt,name=added_by,json=addedBy,proto3" json:"added_by,omitempty"`
	ExpireAt      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=expire_at,json=expireAt,proto3" json:"expire_at,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Blacklist) Reset() {
	*x = Blacklist{}
	mi := &file_proto_risk_risk_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Blacklist) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Blacklist) ProtoMessage() {}

func (x *Blacklist) ProtoReflect() protoreflect.Message {
	mi := &file_proto_risk_risk_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Blacklist.ProtoReflect.Descriptor instead.
func (*Blacklist) Descriptor() ([]byte, []int) {
	return file_proto_risk_risk_proto_rawDescGZIP(), []int{20}
}

func (x *Blacklist) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Blacklist) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *Blacklist) GetEntityValue() string {
	if x != nil {
		return x.EntityValue
	}
	return ""
}

func (x *Blacklist) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *Blacklist) GetAddedBy() string {
	if x != nil {
		return x.AddedBy
	}
	return ""
}

func (x *Blacklist) GetExpireAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpireAt
	}
	return nil
}

func (x *Blacklist) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type AddBlacklistRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityType    string                 `protobuf:"bytes,1,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"`
	EntityValue   string                 `protobuf:"bytes,2,opt,name=entity_value,json=entityValue,proto3" json:"entity_value,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	AddedBy       string                 `protobuf:"bytes,4,opt,name=added_by,json=addedBy,proto3" json:"added_by,omitempty"`
	ExpireAt      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=expire_at,json=expireAt,proto3" json:"expire_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddBlacklistRequest) Reset() {
	*x = AddBlacklistRequest{}
	mi := &file_proto_risk_risk_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddBlacklistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddBlacklistRequest) ProtoMessage() {}

func (x *AddBlacklistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_risk_risk_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddBlacklistRequest.ProtoReflect.Descriptor instead.
func (*AddBlacklistRequest) Descriptor() ([]byte, []int) {
	return file_proto_risk_risk_proto_rawDescGZIP(), []int{21}
}

func (x *AddBlacklistRequest) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *AddBlacklistRequest) GetEntityValue() string {
	if x != nil {
		return x.EntityValue
	}
	return ""
}

func (x *AddBlacklistRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *AddBlacklistRequest) GetAddedBy() string {
	if x != nil {
		return x.AddedBy
	}
	return ""
}

func (x *AddBlacklistRequest) GetExpireAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpireAt
	}
	return nil
}

type BlacklistResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Blacklist     *Blacklist             `protobuf:"bytes,1,opt,name=blacklist,proto3" json:"blacklist,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlacklistResponse) Reset() {
	*x = BlacklistResponse{}
	mi := &file_proto_risk_risk_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlacklistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlacklistResponse) ProtoMessage() {}

func (x *BlacklistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_risk_risk_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlacklistResponse.ProtoReflect.Descriptor instead.
func (*BlacklistResponse) Descriptor() ([]byte, []int) {
	return file_proto_risk_risk_proto_rawDescGZIP(), []int{22}
}

func (x *BlacklistResponse) GetBlacklist() *Blacklist {
	if x != nil {
		return x.Blacklist
	}
	return nil
}

type RemoveBlacklistRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveBlacklistRequest) Reset() {
	*x = RemoveBlacklistRequest{}
	mi := &file_proto_risk_risk_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveBlacklistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveBlacklistRequest) ProtoMessage() {}

func (x *RemoveBlacklistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_risk_risk_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveBlacklistRequest.ProtoReflect.Descriptor instead.
func (*RemoveBlacklistRequest) Descriptor() ([]byte, []int) {
	return file_proto_risk_risk_proto_rawDescGZIP(), []int{23}
}

func (x *RemoveBlacklistRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RemoveBlacklistResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveBlacklistResponse) Reset() {
	*x = RemoveBlacklistResponse{}
	mi := &file_proto_risk_risk_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveBlacklistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveBlacklistResponse) ProtoMessage() {}

func (x *RemoveBlacklistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_risk_risk_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveBlacklistResponse.ProtoReflect.Descriptor instead.
func (*RemoveBlacklistResponse) Descriptor() ([]byte, []int) {
	return file_proto_risk_risk_proto_rawDescGZIP(), []int{24}
}

func (x *RemoveBlacklistResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type CheckBlacklistRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityType    string                 `protobuf:"bytes,1,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"`
	EntityValue   string                 `protobuf:"bytes,2,opt,name=entity_value,json=entityValue,proto3" json:"entity_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckBlacklistRequest) Reset() {
	*x = CheckBlacklistRequest{}
	mi := &file_proto_risk_risk_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckBlacklistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckBlacklistRequest) ProtoMessage() {}

func (x *CheckBlacklistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_risk_risk_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckBlacklistRequest.ProtoReflect.Descriptor instead.
func (*CheckBlacklistRequest) Descriptor() ([]byte, []int) {
	return file_proto_risk_risk_proto_rawDescGZIP(), []int{25}
}

func (x *CheckBlacklistRequest) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *CheckBlacklistRequest) GetEntityValue() string {
	if x != nil {
		return x.EntityValue
	}
	return ""
}

type CheckBlacklistResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsBlacklisted bool                   `protobuf:"varint,1,opt,name=is_blacklisted,json=isBlacklisted,proto3" json:"is_blacklisted,omitempty"`
	Blacklist     *Blacklist             `protobuf:"bytes,2,opt,name=blacklist,proto3" json:"blacklist,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckBlacklistResponse) Reset() {
	*x = CheckBlacklistResponse{}
	mi := &file_proto_risk_risk_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckBlacklistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckBlacklistResponse) ProtoMessage() {}

func (x *CheckBlacklistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_risk_risk_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckBlacklistResponse.ProtoReflect.Descriptor instead.
func (*CheckBlacklistResponse) Descriptor() ([]byte, []int) {
	return file_proto_risk_risk_proto_rawDescGZIP(), []int{26}
}

func (x *CheckBlacklistResponse) GetIsBlacklisted() bool {
	if x != nil {
		return x.IsBlacklisted
	}
	return false
}

func (x *CheckBlacklistResponse) GetBlacklist() *Blacklist {
	if x != nil {
		return x.Blacklist
	}
	return nil
}

type ListBlacklistRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityType    string                 `protobuf:"bytes,1,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBlacklistRequest) Reset() {
	*x = ListBlacklistRequest{}
	mi := &file_proto_risk_risk_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBlacklistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBlacklistRequest) ProtoMessage() {}

func (x *ListBlacklistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_risk_risk_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBlacklistRequest.ProtoReflect.Descriptor instead.
func (*ListBlacklistRequest) Descriptor() ([]byte, []int) {
	return file_proto_risk_risk_proto_rawDescGZIP(), []int{27}
}

func (x *ListBlacklistRequest) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *ListBlacklistRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListBlacklistRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListBlacklistResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Blacklists    []*Blacklist           `protobuf:"bytes,1,rep,name=blacklists,proto3" json:"blacklists,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBlacklistResponse) Reset() {
	*x = ListBlacklistResponse{}
	mi := &file_proto_risk_risk_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBlacklistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBlacklistResponse) ProtoMessage() {}

func (x *ListBlacklistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_risk_risk_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBlacklistResponse.ProtoReflect.Descriptor instead.
func (*ListBlacklistResponse) Descriptor() ([]byte, []int) {
	return file_proto_risk_risk_proto_rawDescGZIP(), []int{28}
}

func (x *ListBlacklistResponse) GetBlacklists() []*Blacklist {
	if x != nil {
		return x.Blacklists
	}
	return nil
}

func (x *ListBlacklistResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_proto_risk_risk_proto protoreflect.FileDescriptor

const file_proto_risk_risk_proto_rawDesc = "" +
	"\n" +
	"\x15proto/risk/risk.proto\x12\x04risk\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xfc\x02\n" +
	"\x13CheckPaymentRequest\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\tR\n" +
	"merchantId\x12\x1d\n" +
	"\n" +
	"related_id\x18\x02 \x01(\tR\trelatedId\x12!\n" +
	"\frelated_type\x18\x03 \x01(\tR\vrelatedType\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x03R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12\x19\n" +
	"\bpayer_ip\x18\x06 \x01(\tR\apayerIp\x12\x1f\n" +
	"\vpayer_email\x18\a \x01(\tR\n" +
	"payerEmail\x12\x1f\n" +
	"\vpayer_phone\x18\b \x01(\tR\n" +
	"payerPhone\x12\x1b\n" +
	"\tdevice_id\x18\t \x01(\tR\bdeviceId\x12%\n" +
	"\x0epayment_method\x18\n" +
	" \x01(\tR\rpaymentMethod\x12-\n" +
	"\x05extra\x18\v \x01(\v2\x17.google.protobuf.StructR\x05extra\"\xa2\x01\n" +
	"\x14CheckPaymentResponse\x12\x1a\n" +
	"\bdecision\x18\x01 \x01(\tR\bdecision\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x05R\x05score\x12\x18\n" +
	"\areasons\x18\x03 \x03(\tR\areasons\x12#\n" +
	"\rmatched_rules\x18\x04 \x03(\tR\fmatchedRules\x12\x19\n" +
	"\bcheck_id\x18\x05 \x01(\tR\acheckId\"\x93\x01\n" +
	"\x1aReportPaymentResultRequest\x12\x19\n" +
	"\bcheck_id\x18\x01 \x01(\tR\acheckId\x12\x16\n" +
	"\x06result\x18\x02 \x01(\tR\x06result\x12\x1d\n" +
	"\n" +
	"error_code\x18\x03 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\"7\n" +
	"\x1bReportPaymentResultResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x8c\x03\n" +
	"\bRiskRule\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\trule_name\x18\x02 \x01(\tR\bruleName\x12\x1b\n" +
	"\trule_type\x18\x03 \x01(\tR\bruleType\x127\n" +
	"\n" +
	"conditions\x18\x04 \x01(\v2\x17.google.protobuf.StructR\n" +
	"conditions\x121\n" +
	"\aactions\x18\x05 \x01(\v2\x17.google.protobuf.StructR\aactions\x12\x1a\n" +
	"\bpriority\x18\x06 \x01(\x05R\bpriority\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12 \n" +
	"\vdescription\x18\b \x01(\tR\vdescription\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xf7\x01\n" +
	"\x11CreateRuleRequest\x12\x1b\n" +
	"\trule_name\x18\x01 \x01(\tR\bruleName\x12\x1b\n" +
	"\trule_type\x18\x02 \x01(\tR\bruleType\x127\n" +
	"\n" +
	"conditions\x18\x03 \x01(\v2\x17.google.protobuf.StructR\n" +
	"conditions\x121\n" +
	"\aactions\x18\x04 \x01(\v2\x17.google.protobuf.StructR\aactions\x12\x1a\n" +
	"\bpriority\x18\x05 \x01(\x05R\bpriority\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\"\xea\x01\n" +
	"\x11UpdateRuleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\trule_name\x18\x02 \x01(\tR\bruleName\x127\n" +
	"\n" +
	"conditions\x18\x03 \x01(\v2\x17.google.protobuf.StructR\n" +
	"conditions\x121\n" +
	"\aactions\x18\x04 \x01(\v2\x17.google.protobuf.StructR\aactions\x12\x1a\n" +
	"\bpriority\x18\x05 \x01(\x05R\bpriority\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\" \n" +
	"\x0eGetRuleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"x\n" +
	"\x10ListRulesRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1b\n" +
	"\trule_type\x18\x03 \x01(\tR\bruleType\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"O\n" +
	"\x11ListRulesResponse\x12$\n" +
	"\x05rules\x18\x01 \x03(\v2\x0e.risk.RiskRuleR\x05rules\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"#\n" +
	"\x11DeleteRuleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\".\n" +
	"\x12DeleteRuleResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"#\n" +
	"\x11EnableRuleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"$\n" +
	"\x12DisableRuleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"2\n" +
	"\fRuleResponse\x12\"\n" +
	"\x04rule\x18\x01 \x01(\v2\x0e.risk.RiskRuleR\x04rule\"\xd1\x02\n" +
	"\tRiskCheck\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vmerchant_id\x18\x02 \x01(\tR\n" +
	"merchantId\x12\x1d\n" +
	"\n" +
	"related_id\x18\x03 \x01(\tR\trelatedId\x12!\n" +
	"\frelated_type\x18\x04 \x01(\tR\vrelatedType\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\x03R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x06 \x01(\tR\bcurrency\x12\x1a\n" +
	"\bdecision\x18\a \x01(\tR\bdecision\x12\x14\n" +
	"\x05score\x18\b \x01(\x05R\x05score\x12\x18\n" +
	"\areasons\x18\t \x03(\tR\areasons\x12\x16\n" +
	"\x06result\x18\n" +
	" \x01(\tR\x06result\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"!\n" +
	"\x0fGetCheckRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"6\n" +
	"\rCheckResponse\x12%\n" +
	"\x05check\x18\x01 \x01(\v2\x0f.risk.RiskCheckR\x05check\"\x92\x02\n" +
	"\x11ListChecksRequest\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\tR\n" +
	"merchantId\x12\x1d\n" +
	"\n" +
	"related_id\x18\x02 \x01(\tR\trelatedId\x12\x1a\n" +
	"\bdecision\x18\x03 \x01(\tR\bdecision\x129\n" +
	"\n" +
	"start_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12\x12\n" +
	"\x04page\x18\x06 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\a \x01(\x05R\bpageSize\"S\n" +
	"\x12ListChecksResponse\x12'\n" +
	"\x06checks\x18\x01 \x03(\v2\x0f.risk.RiskCheckR\x06checks\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\x86\x02\n" +
	"\tBlacklist\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\ventity_type\x18\x02 \x01(\tR\n" +
	"entityType\x12!\n" +
	"\fentity_value\x18\x03 \x01(\tR\ventityValue\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\x12\x19\n" +
	"\badded_by\x18\x05 \x01(\tR\aaddedBy\x127\n" +
	"\texpire_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\bexpireAt\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xc5\x01\n" +
	"\x13AddBlacklistRequest\x12\x1f\n" +
	"\ventity_type\x18\x01 \x01(\tR\n" +
	"entityType\x12!\n" +
	"\fentity_value\x18\x02 \x01(\tR\ventityValue\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12\x19\n" +
	"\badded_by\x18\x04 \x01(\tR\aaddedBy\x127\n" +
	"\texpire_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\bexpireAt\"B\n" +
	"\x11BlacklistResponse\x12-\n" +
	"\tblacklist\x18\x01 \x01(\v2\x0f.risk.BlacklistR\tblacklist\"(\n" +
	"\x16RemoveBlacklistRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"3\n" +
	"\x17RemoveBlacklistResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"[\n" +
	"\x15CheckBlacklistRequest\x12\x1f\n" +
	"\ventity_type\x18\x01 \x01(\tR\n" +
	"entityType\x12!\n" +
	"\fentity_value\x18\x02 \x01(\tR\ventityValue\"n\n" +
	"\x16CheckBlacklistResponse\x12%\n" +
	"\x0eis_blacklisted\x18\x01 \x01(\bR\risBlacklisted\x12-\n" +
	"\tblacklist\x18\x02 \x01(\v2\x0f.risk.BlacklistR\tblacklist\"h\n" +
	"\x14ListBlacklistRequest\x12\x1f\n" +
	"\ventity_type\x18\x01 \x01(\tR\n" +
	"entityType\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"^\n" +
	"\x15ListBlacklistResponse\x12/\n" +
	"\n" +
	"blacklists\x18\x01 \x03(\v2\x0f.risk.BlacklistR\n" +
	"blacklists\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total2\xf6\a\n" +
	"\vRiskService\x12E\n" +
	"\fCheckPayment\x12\x19.risk.CheckPaymentRequest\x1a\x1a.risk.CheckPaymentResponse\x12Z\n" +
	"\x13ReportPaymentResult\x12 .risk.ReportPaymentResultRequest\x1a!.risk.ReportPaymentResultResponse\x129\n" +
	"\n" +
	"CreateRule\x12\x17.risk.CreateRuleRequest\x1a\x12.risk.RuleResponse\x123\n" +
	"\aGetRule\x12\x14.risk.GetRuleRequest\x1a\x12.risk.RuleResponse\x12<\n" +
	"\tListRules\x12\x16.risk.ListRulesRequest\x1a\x17.risk.ListRulesResponse\x129\n" +
	"\n" +
	"UpdateRule\x12\x17.risk.UpdateRuleRequest\x1a\x12.risk.RuleResponse\x12?\n" +
	"\n" +
	"DeleteRule\x12\x17.risk.DeleteRuleRequest\x1a\x18.risk.DeleteRuleResponse\x129\n" +
	"\n" +
	"EnableRule\x12\x17.risk.EnableRuleRequest\x1a\x12.risk.RuleResponse\x12;\n" +
	"\vDisableRule\x12\x18.risk.DisableRuleRequest\x1a\x12.risk.RuleResponse\x126\n" +
	"\bGetCheck\x12\x15.risk.GetCheckRequest\x1a\x13.risk.CheckResponse\x12?\n" +
	"\n" +
	"ListChecks\x12\x17.risk.ListChecksRequest\x1a\x18.risk.ListChecksResponse\x12B\n" +
	"\fAddBlacklist\x12\x19.risk.AddBlacklistRequest\x1a\x17.risk.BlacklistResponse\x12N\n" +
	"\x0fRemoveBlacklist\x12\x1c.risk.RemoveBlacklistRequest\x1a\x1d.risk.RemoveBlacklistResponse\x12K\n" +
	"\x0eCheckBlacklist\x12\x1b.risk.CheckBlacklistRequest\x1a\x1c.risk.CheckBlacklistResponse\x12H\n" +
	"\rListBlacklist\x12\x1a.risk.ListBlacklistRequest\x1a\x1b.risk.ListBlacklistResponseB-Z+github.com/payment-platform/proto/risk;riskb\x06proto3"

var (
	file_proto_risk_risk_proto_rawDescOnce sync.Once
	file_proto_risk_risk_proto_rawDescData []byte
)

func file_proto_risk_risk_proto_rawDescGZIP() []byte {
	file_proto_risk_risk_proto_rawDescOnce.Do(func() {
		file_proto_risk_risk_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_risk_risk_proto_rawDesc), len(file_proto_risk_risk_proto_rawDesc)))
	})
	return file_proto_risk_risk_proto_rawDescData
}

var file_proto_risk_risk_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_proto_risk_risk_proto_goTypes = []any{
	(*CheckPaymentRequest)(nil),         // 0: risk.CheckPaymentRequest
	(*CheckPaymentResponse)(nil),        // 1: risk.CheckPaymentResponse
	(*ReportPaymentResultRequest)(nil),  // 2: risk.ReportPaymentResultRequest
	(*ReportPaymentResultResponse)(nil), // 3: risk.ReportPaymentResultResponse
	(*RiskRule)(nil),                    // 4: risk.RiskRule
	(*CreateRuleRequest)(nil),           // 5: risk.CreateRuleRequest
	(*UpdateRuleRequest)(nil),           // 6: risk.UpdateRuleRequest
	(*GetRuleRequest)(nil),              // 7: risk.GetRuleRequest
	(*ListRulesRequest)(nil),            // 8: risk.ListRulesRequest
	(*ListRulesResponse)(nil),           // 9: risk.ListRulesResponse
	(*DeleteRuleRequest)(nil),           // 10: risk.DeleteRuleRequest
	(*DeleteRuleResponse)(nil),          // 11: risk.DeleteRuleResponse
	(*EnableRuleRequest)(nil),           // 12: risk.EnableRuleRequest
	(*DisableRuleRequest)(nil),          // 13: risk.DisableRuleRequest
	(*RuleResponse)(nil),                // 14: risk.RuleResponse
	(*RiskCheck)(nil),                   // 15: risk.RiskCheck
	(*GetCheckRequest)(nil),             // 16: risk.GetCheckRequest
	(*CheckResponse)(nil),               // 17: risk.CheckResponse
	(*ListChecksRequest)(nil),           // 18: risk.ListChecksRequest
	(*ListChecksResponse)(nil),          // 19: risk.ListChecksResponse
	(*Blacklist)(nil),                   // 20: risk.Blacklist
	(*AddBlacklistRequest)(nil),         // 21: risk.AddBlacklistRequest
	(*BlacklistResponse)(nil),           // 22: risk.BlacklistResponse
	(*RemoveBlacklistRequest)(nil),      // 23: risk.RemoveBlacklistRequest
	(*RemoveBlacklistResponse)(nil),     // 24: risk.RemoveBlacklistResponse
	(*CheckBlacklistRequest)(nil),       // 25: risk.CheckBlacklistRequest
	(*CheckBlacklistResponse)(nil),      // 26: risk.CheckBlacklistResponse
	(*ListBlacklistRequest)(nil),        // 27: risk.ListBlacklistRequest
	(*ListBlacklistResponse)(nil),       // 28: risk.ListBlacklistResponse
	(*structpb.Struct)(nil),             // 29: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil),       // 30: google.protobuf.Timestamp
}
var file_proto_risk_risk_proto_depIdxs = []int32{
	29, // 0: risk.CheckPaymentRequest.extra:type_name -> google.protobuf.Struct
	29, // 1: risk.RiskRule.conditions:type_name -> google.protobuf.Struct
	29, // 2: risk.RiskRule.actions:type_name -> google.protobuf.Struct
	30, // 3: risk.RiskRule.created_at:type_name -> google.protobuf.Timestamp
	30, // 4: risk.RiskRule.updated_at:type_name -> google.protobuf.Timestamp
	29, // 5: risk.CreateRuleRequest.conditions:type_name -> google.protobuf.Struct
	29, // 6: risk.CreateRuleRequest.actions:type_name -> google.protobuf.Struct
	29, // 7: risk.UpdateRuleRequest.conditions:type_name -> google.protobuf.Struct
	29, // 8: risk.UpdateRuleRequest.actions:type_name -> google.protobuf.Struct
	4,  // 9: risk.ListRulesResponse.rules:type_name -> risk.RiskRule
	4,  // 10: risk.RuleResponse.rule:type_name -> risk.RiskRule
	30, // 11: risk.RiskCheck.created_at:type_name -> google.protobuf.Timestamp
	15, // 12: risk.CheckResponse.check:type_name -> risk.RiskCheck
	30, // 13: risk.ListChecksRequest.start_time:type_name -> google.protobuf.Timestamp
	30, // 14: risk.ListChecksRequest.end_time:type_name -> google.protobuf.Timestamp
	15, // 15: risk.ListChecksResponse.checks:type_name -> risk.RiskCheck
	30, // 16: risk.Blacklist.expire_at:type_name -> google.protobuf.Timestamp
	30, // 17: risk.Blacklist.created_at:type_name -> google.protobuf.Timestamp
	30, // 18: risk.AddBlacklistRequest.expire_at:type_name -> google.protobuf.Timestamp
	20, // 19: risk.BlacklistResponse.blacklist:type_name -> risk.Blacklist
	20, // 20: risk.CheckBlacklistResponse.blacklist:type_name -> risk.Blacklist
	20, // 21: risk.ListBlacklistResponse.blacklists:type_name -> risk.Blacklist
	0,  // 22: risk.RiskService.CheckPayment:input_type -> risk.CheckPaymentRequest
	2,  // 23: risk.RiskService.ReportPaymentResult:input_type -> risk.ReportPaymentResultRequest
	5,  // 24: risk.RiskService.CreateRule:input_type -> risk.CreateRuleRequest
	7,  // 25: risk.RiskService.GetRule:input_type -> risk.GetRuleRequest
	8,  // 26: risk.RiskService.ListRules:input_type -> risk.ListRulesRequest
	6,  // 27: risk.RiskService.UpdateRule:input_type -> risk.UpdateRuleRequest
	10, // 28: risk.RiskService.DeleteRule:input_type -> risk.DeleteRuleRequest
	12, // 29: risk.RiskService.EnableRule:input_type -> risk.EnableRuleRequest
	13, // 30: risk.RiskService.DisableRule:input_type -> risk.DisableRuleRequest
	16, // 31: risk.RiskService.GetCheck:input_type -> risk.GetCheckRequest
	18, // 32: risk.RiskService.ListChecks:input_type -> risk.ListChecksRequest
	21, // 33: risk.RiskService.AddBlacklist:input_type -> risk.AddBlacklistRequest
	23, // 34: risk.RiskService.RemoveBlacklist:input_type -> risk.RemoveBlacklistRequest
	25, // 35: risk.RiskService.CheckBlacklist:input_type -> risk.CheckBlacklistRequest
	27, // 36: risk.RiskService.ListBlacklist:input_type -> risk.ListBlacklistRequest
	1,  // 37: risk.RiskService.CheckPayment:output_type -> risk.CheckPaymentResponse
	3,  // 38: risk.RiskService.ReportPaymentResult:output_type -> risk.ReportPaymentResultResponse
	14, // 39: risk.RiskService.CreateRule:output_type -> risk.RuleResponse
	14, // 40: risk.RiskService.GetRule:output_type -> risk.RuleResponse
	9,  // 41: risk.RiskService.ListRules:output_type -> risk.ListRulesResponse
	14, // 42: risk.RiskService.UpdateRule:output_type -> risk.RuleResponse
	11, // 43: risk.RiskService.DeleteRule:output_type -> risk.DeleteRuleResponse
	14, // 44: risk.RiskService.EnableRule:output_type -> risk.RuleResponse
	14, // 45: risk.RiskService.DisableRule:output_type -> risk.RuleResponse
	17, // 46: risk.RiskService.GetCheck:output_type -> risk.CheckResponse
	19, // 47: risk.RiskService.ListChecks:output_type -> risk.ListChecksResponse
	22, // 48: risk.RiskService.AddBlacklist:output_type -> risk.BlacklistResponse
	24, // 49: risk.RiskService.RemoveBlacklist:output_type -> risk.RemoveBlacklistResponse
	26, // 50: risk.RiskService.CheckBlacklist:output_type -> risk.CheckBlacklistResponse
	28, // 51: risk.RiskService.ListBlacklist:output_type -> risk.ListBlacklistResponse
	37, // [37:52] is the sub-list for method output_type
	22, // [22:37] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_proto_risk_risk_proto_init() }
func file_proto_risk_risk_proto_init() {
	if File_proto_risk_risk_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_risk_risk_proto_rawDesc), len(file_proto_risk_risk_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_risk_risk_proto_goTypes,
		DependencyIndexes: file_proto_risk_risk_proto_depIdxs,
		MessageInfos:      file_proto_risk_risk_proto_msgTypes,
	}.Build()
	File_proto_risk_risk_proto = out.File
	file_proto_risk_risk_proto_goTypes = nil
	file_proto_risk_risk_proto_depIdxs = nil
}
