// Package api_docs Code generated by swaggo/swag. DO NOT EDIT
package api_docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "email": "support@payment-platform.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/channel/config": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Channel"
                ],
                "summary": "列出所有渠道配置",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/channel/config/{channel}": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Channel"
                ],
                "summary": "获取渠道配置",
                "parameters": [
                    {
                        "type": "string",
                        "description": "渠道名称",
                        "name": "channel",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/channel/payments": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Channel"
                ],
                "summary": "创建支付",
                "parameters": [
                    {
                        "description": "创建支付请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/payment-platform_channel-adapter_internal_service.CreatePaymentRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/payment-platform_channel-adapter_internal_service.CreatePaymentResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/channel/payments/{payment_no}": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Channel"
                ],
                "summary": "查询支付状态",
                "parameters": [
                    {
                        "type": "string",
                        "description": "支付流水号",
                        "name": "payment_no",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/payment-platform_channel-adapter_internal_service.QueryPaymentResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/channel/payments/{payment_no}/cancel": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Channel"
                ],
                "summary": "取消支付",
                "parameters": [
                    {
                        "type": "string",
                        "description": "支付流水号",
                        "name": "payment_no",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/channel/query": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Channel"
                ],
                "summary": "查询支付状态（兼容接口）",
                "parameters": [
                    {
                        "description": "查询请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/payment-platform_channel-adapter_internal_service.QueryPaymentResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/channel/refunds": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Channel"
                ],
                "summary": "创建退款",
                "parameters": [
                    {
                        "description": "创建退款请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/payment-platform_channel-adapter_internal_service.CreateRefundRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/payment-platform_channel-adapter_internal_service.CreateRefundResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/channel/refunds/{refund_no}": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Channel"
                ],
                "summary": "查询退款状态",
                "parameters": [
                    {
                        "type": "string",
                        "description": "退款流水号",
                        "name": "refund_no",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/payment-platform_channel-adapter_internal_service.QueryRefundResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/webhooks/paypal": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Webhook"
                ],
                "summary": "处理 PayPal Webhook 回调",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/webhooks/stripe": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Webhook"
                ],
                "summary": "处理 Stripe Webhook 回调",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "payment-platform_channel-adapter_internal_service.CreatePaymentRequest": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "integer"
                },
                "callback_url": {
                    "type": "string"
                },
                "cancel_url": {
                    "type": "string"
                },
                "channel": {
                    "type": "string"
                },
                "currency": {
                    "type": "string"
                },
                "customer_email": {
                    "type": "string"
                },
                "customer_name": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "extra": {
                    "type": "object",
                    "additionalProperties": true
                },
                "merchant_id": {
                    "type": "string"
                },
                "order_no": {
                    "type": "string"
                },
                "payment_no": {
                    "type": "string"
                },
                "success_url": {
                    "type": "string"
                }
            }
        },
        "payment-platform_channel-adapter_internal_service.CreatePaymentResponse": {
            "type": "object",
            "properties": {
                "channel_trade_no": {
                    "type": "string"
                },
                "client_secret": {
                    "type": "string"
                },
                "extra": {
                    "type": "object",
                    "additionalProperties": true
                },
                "payment_no": {
                    "type": "string"
                },
                "payment_url": {
                    "type": "string"
                },
                "qr_code_url": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "payment-platform_channel-adapter_internal_service.CreateRefundRequest": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "integer"
                },
                "currency": {
                    "type": "string"
                },
                "merchant_id": {
                    "type": "string"
                },
                "payment_no": {
                    "type": "string"
                },
                "reason": {
                    "type": "string"
                },
                "refund_no": {
                    "type": "string"
                }
            }
        },
        "payment-platform_channel-adapter_internal_service.CreateRefundResponse": {
            "type": "object",
            "properties": {
                "channel_refund_no": {
                    "type": "string"
                },
                "refund_no": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "payment-platform_channel-adapter_internal_service.QueryPaymentResponse": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "integer"
                },
                "channel_trade_no": {
                    "type": "string"
                },
                "currency": {
                    "type": "string"
                },
                "paid_at": {
                    "type": "string"
                },
                "payment_method": {
                    "type": "string"
                },
                "payment_method_details": {
                    "type": "object",
                    "additionalProperties": true
                },
                "payment_no": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "payment-platform_channel-adapter_internal_service.QueryRefundResponse": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "integer"
                },
                "channel_refund_no": {
                    "type": "string"
                },
                "currency": {
                    "type": "string"
                },
                "refund_no": {
                    "type": "string"
                },
                "refunded_at": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Type \"Bearer\" followed by a space and JWT token.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8005",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Channel Adapter API",
	Description:      "支付平台支付渠道适配器服务API文档",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
